// 支持的语言列表（用于下拉框）
window.LANG_LIST = [
    { code: 'en', name: 'English' },
    { code: 'ca', name: 'Català' },
    { code: 'cs', name: 'Čeština' },
    { code: 'da', name: 'Dansk' },
    { code: 'de', name: 'Deutsch' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'es-ES', name: 'Español (España)' },
    { code: 'es-419', name: 'Español (América Latina)' },
    { code: 'eu', name: 'Euskara' },
    { code: 'fi', name: 'Suomi' },
    { code: 'fr', name: 'Français' },
    { code: 'fr-CA', name: 'Français Canadien' },
    { code: 'hr', name: 'Hrvatski' },
    { code: 'hu', name: 'Magyar' },
    { code: 'id', name: 'Bahasa Indonesia' },
    { code: 'it', name: 'Italiano' },
    { code: 'ja', name: '日本語' },
    { code: 'kk', name: 'Қазақша' },
    { code: 'ko', name: '한국어' },
    { code: 'nl', name: 'Nederlands' },
    { code: 'pl', name: 'Polski' },
    { code: 'pt-PT', name: 'Português Europeu' },
    { code: 'pt-BR', name: 'Português Brasileiro' },
    { code: 'ro', name: 'Română' },
    { code: 'ru', name: 'Русский' },
    { code: 'sk', name: 'Slovenský' },
    { code: 'sl', name: 'Slovenščina' },
    { code: 'sv', name: 'Svenska' },
    { code: 'th', name: 'ภาษาไทย' },
    { code: 'uk', name: 'Українська' },
    { code: 'vi', name: 'Tiếng Việt' },
    { code: 'zh-CN', name: '简体中文' },
    { code: 'zh-TW', name: '繁體中文' }
];

// 翻译资源 (key: 语言代码, value: 翻译对象)
// 未提供的键将自动回退到英文 (en)
window.TRANSLATIONS = {
    // 英文（完整）
    'en': {
        'nav.home': 'Home',
        'nav.season': 'Season Rankings',
        'nav.active': 'Active Rankings',
        'nav.region': 'Regional Rankings',
        'nav.comprehensive': 'Comprehensive Rankings',
        'nav.record': 'Regional Records',
        'season.title': 'Season Rankings',
        'season.subtitle': 'This page shows season rankings, taking one year as a cycle (e.g., 2026 season). It ranks players\' best results in the current season to reflect their highest competitive level. All ranking results are from official WCA competitions.',
        'active.title': 'Active Rankings',
        'active.subtitle': 'This page shows active rankings, taking three years as a period. It ranks players\' best results in the last three years to reflect their recent competitive level. Players with no competition records for more than three years are not included. All ranking results are from official WCA competitions.',
        'region.title': 'Regional Rankings',
        'region.subtitle': 'This page shows rankings of Chinese players within their provinces/cities. For players who did not select their region on Cubing China before May 2018, they are automatically assigned to the fictional "Shenshou Valley" (see homepage announcement for details). All ranking results are from official WCA competitions.',
        'comprehensive.title': 'Comprehensive Rankings',
        'comprehensive.subtitle': 'This page calculates the sum of ranks across multiple events and ranks players accordingly.',
        'record.title': 'Regional Records',
        'record.subtitle': 'This page shows records for all provinces and cities in China across all WCA events. All results are from official WCA rankings.',
        'filter.region': 'Region',
        'filter.project': 'Event',
        'filter.gender': 'Gender',
        'filter.period': 'Period',
        'filter.province': 'Province',
        'filter.city': 'City',
        'filter.source': 'Ranking Type',
        'filter.dataset': 'Sub-dataset',
        'gender.all': 'All',
        'gender.male': 'Male',
        'gender.female': 'Female',
        'gender.unknown': 'Unknown',
        'btn.single': 'Single',
        'btn.average': 'Average',
        'btn.refresh': 'Refresh',
        'table.rank': 'Rank',
        'table.name': 'Name',
        'table.country': 'Country',
        'table.province': 'Province',
        'table.city': 'City',
        'table.result': 'Result',
        'table.competition': 'Competition',
        'table.wcaid': 'WCA ID',
        'table.event': 'Event',
        'table.events_count': 'Events',
        'table.total_rank': 'Total Rank',
        'current.single': 'Single',
        'current.average': 'Average',
        'current.historical': 'Historical',
        'current.season': 'Season',
        'current.active': 'Active',
        'loading': 'Loading',
        'loading_failed': 'Data loading failed',
        'no_data': 'No data',
        'announcement.region.title': 'About Regional Information',
        'announcement.region.content': 'Since May 2018, Cubing China has stopped displaying players\' cities. Players without city information after that date are assigned to the fictional "Shenshou Valley" by the author. The current province/city data comes from data crawled by 魔友赵吉波 before the cancellation. Many thanks to him!',
        'announcement.launch.title': 'Website Launch',
        'announcement.launch.content': 'XCUBING website is now online. It provides season rankings, active rankings, regional rankings, comprehensive rankings, and regional records from WCA events. We welcome all cubers to experience the site and provide feedback on any issues or suggestions. If you encounter any errors, please contact the author at: xcubing@qq.com.',
        'comp.select_events': 'Select events (click to choose)',
        'comp.current': '{source} - {count} event(s) selected ({type})',
        'comp.calculating': 'Calculating comprehensive rankings, please wait...',
        'record.no_record': 'No record',
        'all_cities': 'All cities in province',
    },

    // 简体中文（完整）
    'zh-CN': {
        'nav.home': '首页',
        'nav.season': '赛季排名',
        'nav.active': '现役排名',
        'nav.region': '省市排名',
        'nav.comprehensive': '综合排名',
        'nav.record': '省市纪录',
        'season.title': '赛季排名',
        'season.subtitle': '本页面为赛季排名，以一年为一个周期（如2026年即为2026赛季），将参赛选手在这个赛季的最佳成绩进行排名，以反映他们在当前赛季的最高竞技水平。所有的排名成绩源自WCA赛事的官方排名。',
        'active.title': '现役排名',
        'active.subtitle': '本页面为现役排名，以三年为期，将参赛选手在此期间的最佳成绩进行排名，以反映他们在最近三年的最高竞技水平，超过三年无参赛记录的选手不被列入排名。所有的排名成绩源自WCA赛事的官方排名。',
        'region.title': '省市排名',
        'region.subtitle': '本页面为省市排名，可以查看中国选手在其归属地的排名，对于截至2018年5月前没有在粗饼网选择归属地的选手，系统将自动将其归入本站虚构的秘境——神手谷（具体缘由详见首页公告）。所有的排名成绩源自WCA赛事的官方排名。',
        'comprehensive.title': '综合排名',
        'comprehensive.subtitle': '本页面为综合排名，可计算选手在多个项目的排名总和并进行排名。',
        'record.title': '省市纪录',
        'record.subtitle': '本页面为省市纪录，可以查看中国所有有参赛选手的省份及城市在WCA所有项目的纪录。所有的成绩源自WCA官方排名。',
        'filter.region': '地区',
        'filter.project': '项目',
        'filter.gender': '性别',
        'filter.period': '时期',
        'filter.province': '省份',
        'filter.city': '城市',
        'filter.source': '排名类型',
        'filter.dataset': '时期',
        'gender.all': '所有',
        'gender.male': '男',
        'gender.female': '女',
        'gender.unknown': '未知',
        'btn.single': '单次',
        'btn.average': '平均',
        'btn.refresh': '刷新',
        'table.rank': '排名',
        'table.name': '姓名',
        'table.country': '国家',
        'table.province': '省份',
        'table.city': '城市',
        'table.result': '成绩',
        'table.competition': '比赛',
        'table.wcaid': 'WCA ID',
        'table.event': '项目',
        'table.events_count': '参与项目数',
        'table.total_rank': '排名总和',
        'current.single': '单次',
        'current.average': '平均',
        'current.historical': '历史',
        'current.season': '赛季',
        'current.active': '现役',
        'loading': '加载中',
        'loading_failed': '数据加载失败',
        'no_data': '暂无数据',
        'announcement.region.title': '关于省市信息',
        'announcement.region.content': '2018年5月粗饼网取消选手所在城市显示，由于现在已无法从粗饼网获取选手城市，故而此后的选手在本站被作者归入了不存在的神手谷。目前使用的选手省市信息源自魔友赵吉波在取消前爬取的数据，非常感谢前辈留下的数据！',
        'announcement.launch.title': '网站上线',
        'announcement.launch.content': 'XCUBING网站正式上线运行，网站目前提供WCA赛事的赛季、现役、省市、综合排名及省市纪录功能，诚挚欢迎广大魔友积极体验并对网站在页面显示、功能使用等方面存在的问题和不足提出宝贵意见和建议。如您在访问网站过程中发现任何错误、故障，请及时通过以下方式反馈：作者邮箱：xcubing@qq.com。',
        'comp.select_events': '项目(点击选择)',
        'comp.current': '{source} - 已选{count}个项目 ({type})',
        'comp.calculating': '正在计算综合排名，请稍候...',
        'record.no_record': '暂无纪录',
        'all_cities': '全省',
    },

    // 繁体中文（基础翻译，基于简体转换，长文本需人工完善）
    'zh-TW': {
        'nav.home': '首頁',
        'nav.season': '賽季排名',
        'nav.active': '現役排名',
        'nav.region': '省市排名',
        'nav.comprehensive': '綜合排名',
        'nav.record': '省市紀錄',
        'season.title': '賽季排名',
        'active.title': '現役排名',
        'region.title': '省市排名',
        'comprehensive.title': '綜合排名',
        'record.title': '省市紀錄',
        'filter.region': '地區',
        'filter.project': '項目',
        'filter.gender': '性別',
        'filter.period': '時期',
        'filter.province': '省份',
        'filter.city': '城市',
        'filter.source': '排名類型',
        'filter.dataset': '時期',
        'gender.all': '所有',
        'gender.male': '男',
        'gender.female': '女',
        'gender.unknown': '未知',
        'btn.single': '單次',
        'btn.average': '平均',
        'btn.refresh': '重新整理',
        'table.rank': '排名',
        'table.name': '姓名',
        'table.country': '國家',
        'table.province': '省份',
        'table.city': '城市',
        'table.result': '成績',
        'table.competition': '比賽',
        'table.wcaid': 'WCA ID',
        'table.event': '項目',
        'table.events_count': '參與項目數',
        'table.total_rank': '排名總和',
        'current.single': '單次',
        'current.average': '平均',
        'current.historical': '歷史',
        'current.season': '賽季',
        'current.active': '現役',
        'loading': '載入中',
        'loading_failed': '資料載入失敗',
        'no_data': '暫無資料',
        'comp.select_events': '項目(點擊選擇)',
        'comp.current': '{source} - 已選{count}個項目 ({type})',
        'comp.calculating': '正在計算綜合排名，請稍候...',
        'record.no_record': '暫無紀錄',
        'all_cities': '全省',
    },

    // 以下为其他语言的基础翻译（短文本已尽力提供，长文本可后续完善）
    'ca': {
        'nav.home': 'Inici',
        'nav.season': 'Rànquings de Temporada',
        'nav.active': 'Rànquings Actius',
        'nav.region': 'Rànquings Regionals',
        'nav.comprehensive': 'Rànquings Comprensius',
        'nav.record': 'Rècords Regionals',
        'filter.region': 'Regió',
        'filter.project': 'Esdeveniment',
        'filter.gender': 'Gènere',
        'filter.period': 'Període',
        'filter.province': 'Província',
        'filter.city': 'Ciutat',
        'filter.source': 'Tipus de Rànquing',
        'filter.dataset': 'Subconjunt',
        'gender.all': 'Tots',
        'gender.male': 'Home',
        'gender.female': 'Dona',
        'gender.unknown': 'Desconegut',
        'btn.single': 'Individual',
        'btn.average': 'Mitjana',
        'btn.refresh': 'Actualitzar',
        'table.rank': 'Posició',
        'table.name': 'Nom',
        'table.country': 'País',
        'table.province': 'Província',
        'table.city': 'Ciutat',
        'table.result': 'Resultat',
        'table.competition': 'Competició',
        'table.wcaid': 'ID WCA',
        'table.event': 'Esdeveniment',
        'table.events_count': 'Esdeveniments',
        'table.total_rank': 'Suma de Posicions',
        'current.single': 'Individual',
        'current.average': 'Mitjana',
        'current.historical': 'Històric',
        'current.season': 'Temporada',
        'current.active': 'Actiu',
        'loading': 'Carregant',
        'loading_failed': 'Error en carregar les dades',
        'no_data': 'Sense dades',
        'comp.select_events': 'Selecciona esdeveniments (clic per triar)',
        'comp.current': '{source} - {count} esdeveniment(s) seleccionat(s) ({type})',
        'comp.calculating': 'Calculant rànquings comprensius, espereu...',
        'record.no_record': 'Sense rècord',
        'all_cities': 'Totes les ciutats de la província',
    },
    'cs': {
        'nav.home': 'Domů',
        'nav.season': 'Sezónní žebříčky',
        'nav.active': 'Aktivní žebříčky',
        'nav.region': 'Regionální žebříčky',
        'nav.comprehensive': 'Komplexní žebříčky',
        'nav.record': 'Regionální rekordy',
        'filter.region': 'Region',
        'filter.project': 'Disciplína',
        'filter.gender': 'Pohlaví',
        'filter.period': 'Období',
        'filter.province': 'Provincie',
        'filter.city': 'Město',
        'filter.source': 'Typ žebříčku',
        'filter.dataset': 'Podmnožina',
        'gender.all': 'Vše',
        'gender.male': 'Muž',
        'gender.female': 'Žena',
        'gender.unknown': 'Neznámé',
        'btn.single': 'Jednotlivě',
        'btn.average': 'Průměr',
        'btn.refresh': 'Obnovit',
        'table.rank': 'Pořadí',
        'table.name': 'Jméno',
        'table.country': 'Země',
        'table.province': 'Provincie',
        'table.city': 'Město',
        'table.result': 'Výsledek',
        'table.competition': 'Soutěž',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplína',
        'table.events_count': 'Disciplíny',
        'table.total_rank': 'Součet pořadí',
        'current.single': 'Jednotlivě',
        'current.average': 'Průměr',
        'current.historical': 'Historický',
        'current.season': 'Sezóna',
        'current.active': 'Aktivní',
        'loading': 'Načítání',
        'loading_failed': 'Načítání selhalo',
        'no_data': 'Žádná data',
        'comp.select_events': 'Vyberte disciplíny (kliknutím vyberete)',
        'comp.current': '{source} - vybráno {count} disciplín ({type})',
        'comp.calculating': 'Probíhá výpočet komplexního žebříčku, čekejte...',
        'record.no_record': 'Žádný rekord',
        'all_cities': 'Všechna města v provincii',
    },
    'da': {
        'nav.home': 'Hjem',
        'nav.season': 'Sæsonranglister',
        'nav.active': 'Aktive ranglister',
        'nav.region': 'Regionale ranglister',
        'nav.comprehensive': 'Omfattende ranglister',
        'nav.record': 'Regionale rekorder',
        'filter.region': 'Område',
        'filter.project': 'Disciplin',
        'filter.gender': 'Køn',
        'filter.period': 'Periode',
        'filter.province': 'Provins',
        'filter.city': 'By',
        'filter.source': 'Ranglistetype',
        'filter.dataset': 'Underdatasæt',
        'gender.all': 'Alle',
        'gender.male': 'Mand',
        'gender.female': 'Kvinde',
        'gender.unknown': 'Ukendt',
        'btn.single': 'Enkelt',
        'btn.average': 'Gennemsnit',
        'btn.refresh': 'Opdater',
        'table.rank': 'Placering',
        'table.name': 'Navn',
        'table.country': 'Land',
        'table.province': 'Provins',
        'table.city': 'By',
        'table.result': 'Resultat',
        'table.competition': 'Konkurrence',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplin',
        'table.events_count': 'Discipliner',
        'table.total_rank': 'Samlet placering',
        'current.single': 'Enkelt',
        'current.average': 'Gennemsnit',
        'current.historical': 'Historisk',
        'current.season': 'Sæson',
        'current.active': 'Aktiv',
        'loading': 'Indlæser',
        'loading_failed': 'Indlæsning mislykkedes',
        'no_data': 'Ingen data',
        'comp.select_events': 'Vælg discipliner (klik for at vælge)',
        'comp.current': '{source} - {count} disciplin(er) valgt ({type})',
        'comp.calculating': 'Beregner omfattende ranglister, vent venligst...',
        'record.no_record': 'Ingen rekord',
        'all_cities': 'Alle byer i provinsen',
    },
    'de': {
        'nav.home': 'Startseite',
        'nav.season': 'Saison-Rankings',
        'nav.active': 'Aktive Rankings',
        'nav.region': 'Regionale Rankings',
        'nav.comprehensive': 'Gesamtranglisten',
        'nav.record': 'Regionale Rekorde',
        'filter.region': 'Region',
        'filter.project': 'Disziplin',
        'filter.gender': 'Geschlecht',
        'filter.period': 'Zeitraum',
        'filter.province': 'Provinz',
        'filter.city': 'Stadt',
        'filter.source': 'Ranking-Typ',
        'filter.dataset': 'Teildatensatz',
        'gender.all': 'Alle',
        'gender.male': 'Männlich',
        'gender.female': 'Weiblich',
        'gender.unknown': 'Unbekannt',
        'btn.single': 'Einzel',
        'btn.average': 'Durchschnitt',
        'btn.refresh': 'Aktualisieren',
        'table.rank': 'Rang',
        'table.name': 'Name',
        'table.country': 'Land',
        'table.province': 'Provinz',
        'table.city': 'Stadt',
        'table.result': 'Ergebnis',
        'table.competition': 'Wettbewerb',
        'table.wcaid': 'WCA-ID',
        'table.event': 'Disziplin',
        'table.events_count': 'Disziplinen',
        'table.total_rank': 'Gesamtrang',
        'current.single': 'Einzel',
        'current.average': 'Durchschnitt',
        'current.historical': 'Historisch',
        'current.season': 'Saison',
        'current.active': 'Aktiv',
        'loading': 'Laden',
        'loading_failed': 'Laden fehlgeschlagen',
        'no_data': 'Keine Daten',
        'comp.select_events': 'Disziplinen auswählen (klicken zum Auswählen)',
        'comp.current': '{source} - {count} Disziplin(en) ausgewählt ({type})',
        'comp.calculating': 'Gesamtrangliste wird berechnet, bitte warten...',
        'record.no_record': 'Kein Rekord',
        'all_cities': 'Alle Städte in der Provinz',
    },
    'eo': {
        'nav.home': 'Ĉefpaĝo',
        'nav.season': 'Sezonaj Rangotabeloj',
        'nav.active': 'Aktivaj Rangotabeloj',
        'nav.region': 'Regionaj Rangotabeloj',
        'nav.comprehensive': 'Ĝeneralaj Rangotabeloj',
        'nav.record': 'Regionaj Rekordoj',
        'filter.region': 'Regiono',
        'filter.project': 'Disciplino',
        'filter.gender': 'Sekso',
        'filter.period': 'Periodo',
        'filter.province': 'Provinco',
        'filter.city': 'Urbo',
        'filter.source': 'Rangotabela Tipo',
        'filter.dataset': 'Subdatokolekto',
        'gender.all': 'Ĉiuj',
        'gender.male': 'Vira',
        'gender.female': 'Ina',
        'gender.unknown': 'Nekonata',
        'btn.single': 'Unuopa',
        'btn.average': 'Meznombro',
        'btn.refresh': 'Refreŝigi',
        'table.rank': 'Rango',
        'table.name': 'Nomo',
        'table.country': 'Lando',
        'table.province': 'Provinco',
        'table.city': 'Urbo',
        'table.result': 'Rezulto',
        'table.competition': 'Konkurso',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplino',
        'table.events_count': 'Disciplinoj',
        'table.total_rank': 'Suma Rango',
        'current.single': 'Unuopa',
        'current.average': 'Meznombro',
        'current.historical': 'Historia',
        'current.season': 'Sezono',
        'current.active': 'Aktiva',
        'loading': 'Ŝarĝante',
        'loading_failed': 'Ŝarĝo malsukcesis',
        'no_data': 'Neniuj datumoj',
        'comp.select_events': 'Elektu disciplinojn (alklaku por elekti)',
        'comp.current': '{source} - {count} elektita(j) disciplino(j) ({type})',
        'comp.calculating': 'Kalkulante ĝeneralajn rangotabelojn, bonvolu atendi...',
        'record.no_record': 'Nenia rekordo',
        'all_cities': 'Ĉiuj urboj en la provinco',
    },
    'es-ES': {
        'nav.home': 'Inicio',
        'nav.season': 'Rankings de Temporada',
        'nav.active': 'Rankings Activos',
        'nav.region': 'Rankings Regionales',
        'nav.comprehensive': 'Rankings Integrales',
        'nav.record': 'Récords Regionales',
        'filter.region': 'Región',
        'filter.project': 'Evento',
        'filter.gender': 'Género',
        'filter.period': 'Período',
        'filter.province': 'Provincia',
        'filter.city': 'Ciudad',
        'filter.source': 'Tipo de Ranking',
        'filter.dataset': 'Subconjunto',
        'gender.all': 'Todos',
        'gender.male': 'Hombre',
        'gender.female': 'Mujer',
        'gender.unknown': 'Desconocido',
        'btn.single': 'Individual',
        'btn.average': 'Promedio',
        'btn.refresh': 'Actualizar',
        'table.rank': 'Posición',
        'table.name': 'Nombre',
        'table.country': 'País',
        'table.province': 'Provincia',
        'table.city': 'Ciudad',
        'table.result': 'Resultado',
        'table.competition': 'Competición',
        'table.wcaid': 'ID WCA',
        'table.event': 'Evento',
        'table.events_count': 'Eventos',
        'table.total_rank': 'Suma de Posiciones',
        'current.single': 'Individual',
        'current.average': 'Promedio',
        'current.historical': 'Histórico',
        'current.season': 'Temporada',
        'current.active': 'Activo',
        'loading': 'Cargando',
        'loading_failed': 'Error al cargar datos',
        'no_data': 'Sin datos',
        'comp.select_events': 'Selecciona eventos (clic para elegir)',
        'comp.current': '{source} - {count} evento(s) seleccionado(s) ({type})',
        'comp.calculating': 'Calculando rankings integrales, espere...',
        'record.no_record': 'Sin récord',
        'all_cities': 'Todas las ciudades de la provincia',
    },
    'es-419': {
        'nav.home': 'Inicio',
        'nav.season': 'Rankings de Temporada',
        'nav.active': 'Rankings Activos',
        'nav.region': 'Rankings Regionales',
        'nav.comprehensive': 'Rankings Integrales',
        'nav.record': 'Récords Regionales',
        'filter.region': 'Región',
        'filter.project': 'Evento',
        'filter.gender': 'Género',
        'filter.period': 'Período',
        'filter.province': 'Provincia',
        'filter.city': 'Ciudad',
        'filter.source': 'Tipo de Ranking',
        'filter.dataset': 'Subconjunto',
        'gender.all': 'Todos',
        'gender.male': 'Hombre',
        'gender.female': 'Mujer',
        'gender.unknown': 'Desconocido',
        'btn.single': 'Individual',
        'btn.average': 'Promedio',
        'btn.refresh': 'Actualizar',
        'table.rank': 'Posición',
        'table.name': 'Nombre',
        'table.country': 'País',
        'table.province': 'Provincia',
        'table.city': 'Ciudad',
        'table.result': 'Resultado',
        'table.competition': 'Competencia',
        'table.wcaid': 'ID WCA',
        'table.event': 'Evento',
        'table.events_count': 'Eventos',
        'table.total_rank': 'Suma de Posiciones',
        'current.single': 'Individual',
        'current.average': 'Promedio',
        'current.historical': 'Histórico',
        'current.season': 'Temporada',
        'current.active': 'Activo',
        'loading': 'Cargando',
        'loading_failed': 'Error al cargar datos',
        'no_data': 'Sin datos',
        'comp.select_events': 'Selecciona eventos (clic para elegir)',
        'comp.current': '{source} - {count} evento(s) seleccionado(s) ({type})',
        'comp.calculating': 'Calculando rankings integrales, espere...',
        'record.no_record': 'Sin récord',
        'all_cities': 'Todas las ciudades de la provincia',
    },
    'eu': {
        'nav.home': 'Hasiera',
        'nav.season': 'Denboraldiko sailkapenak',
        'nav.active': 'Sailkapen aktiboak',
        'nav.region': 'Eskualdeko sailkapenak',
        'nav.comprehensive': 'Sailkapen integralak',
        'nav.record': 'Eskualdeko errekorrak',
        'filter.region': 'Eskualdea',
        'filter.project': 'Proba',
        'filter.gender': 'Generoa',
        'filter.period': 'Epea',
        'filter.province': 'Probintzia',
        'filter.city': 'Hiria',
        'filter.source': 'Sailkapen mota',
        'filter.dataset': 'Azpimultzoa',
        'gender.all': 'Guztiak',
        'gender.male': 'Gizona',
        'gender.female': 'Emakumea',
        'gender.unknown': 'Ezezaguna',
        'btn.single': 'Bakarka',
        'btn.average': 'Batezbestekoa',
        'btn.refresh': 'Freskatu',
        'table.rank': 'Postua',
        'table.name': 'Izena',
        'table.country': 'Herrialdea',
        'table.province': 'Probintzia',
        'table.city': 'Hiria',
        'table.result': 'Emaitza',
        'table.competition': 'Lehiaketa',
        'table.wcaid': 'WCA ID',
        'table.event': 'Proba',
        'table.events_count': 'Probak',
        'table.total_rank': 'Postuen batura',
        'current.single': 'Bakarka',
        'current.average': 'Batezbestekoa',
        'current.historical': 'Historikoa',
        'current.season': 'Denboraldia',
        'current.active': 'Aktiboa',
        'loading': 'Kargatzen',
        'loading_failed': 'Kargatzeak huts egin du',
        'no_data': 'Daturik ez',
        'comp.select_events': 'Hautatu probak (klik egin aukeratzeko)',
        'comp.current': '{source} - {count} proba hautatu dira ({type})',
        'comp.calculating': 'Sailkapen integralak kalkulatzen, itxaron mesedez...',
        'record.no_record': 'Errekorrik ez',
        'all_cities': 'Probintziako hiri guztiak',
    },
    'fi': {
        'nav.home': 'Koti',
        'nav.season': 'Kauden rankingit',
        'nav.active': 'Aktiiviset rankingit',
        'nav.region': 'Alueelliset rankingit',
        'nav.comprehensive': 'Kattavat rankingit',
        'nav.record': 'Alueelliset ennätykset',
        'filter.region': 'Alue',
        'filter.project': 'Laji',
        'filter.gender': 'Sukupuoli',
        'filter.period': 'Ajanjakso',
        'filter.province': 'Maakunta',
        'filter.city': 'Kaupunki',
        'filter.source': 'Ranking-tyyppi',
        'filter.dataset': 'Osajoukko',
        'gender.all': 'Kaikki',
        'gender.male': 'Mies',
        'gender.female': 'Nainen',
        'gender.unknown': 'Tuntematon',
        'btn.single': 'Yksittäinen',
        'btn.average': 'Keskiarvo',
        'btn.refresh': 'Päivitä',
        'table.rank': 'Sijoitus',
        'table.name': 'Nimi',
        'table.country': 'Maa',
        'table.province': 'Maakunta',
        'table.city': 'Kaupunki',
        'table.result': 'Tulos',
        'table.competition': 'Kilpailu',
        'table.wcaid': 'WCA-tunnus',
        'table.event': 'Laji',
        'table.events_count': 'Lajit',
        'table.total_rank': 'Sijoitusten summa',
        'current.single': 'Yksittäinen',
        'current.average': 'Keskiarvo',
        'current.historical': 'Historiallinen',
        'current.season': 'Kausi',
        'current.active': 'Aktiivinen',
        'loading': 'Ladataan',
        'loading_failed': 'Tietojen lataus epäonnistui',
        'no_data': 'Ei tietoja',
        'comp.select_events': 'Valitse lajit (klikkaa valitaksesi)',
        'comp.current': '{source} - {count} lajia valittu ({type})',
        'comp.calculating': 'Lasketaan kattavia rankingeja, odota...',
        'record.no_record': 'Ei ennätystä',
        'all_cities': 'Kaikki maakunnan kaupungit',
    },
    'fr': {
        'nav.home': 'Accueil',
        'nav.season': 'Classements de saison',
        'nav.active': 'Classements actifs',
        'nav.region': 'Classements régionaux',
        'nav.comprehensive': 'Classements complets',
        'nav.record': 'Records régionaux',
        'filter.region': 'Région',
        'filter.project': 'Épreuve',
        'filter.gender': 'Genre',
        'filter.period': 'Période',
        'filter.province': 'Province',
        'filter.city': 'Ville',
        'filter.source': 'Type de classement',
        'filter.dataset': 'Sous-ensemble',
        'gender.all': 'Tous',
        'gender.male': 'Homme',
        'gender.female': 'Femme',
        'gender.unknown': 'Inconnu',
        'btn.single': 'Simple',
        'btn.average': 'Moyenne',
        'btn.refresh': 'Actualiser',
        'table.rank': 'Rang',
        'table.name': 'Nom',
        'table.country': 'Pays',
        'table.province': 'Province',
        'table.city': 'Ville',
        'table.result': 'Résultat',
        'table.competition': 'Compétition',
        'table.wcaid': 'ID WCA',
        'table.event': 'Épreuve',
        'table.events_count': 'Épreuves',
        'table.total_rank': 'Somme des rangs',
        'current.single': 'Simple',
        'current.average': 'Moyenne',
        'current.historical': 'Historique',
        'current.season': 'Saison',
        'current.active': 'Actif',
        'loading': 'Chargement',
        'loading_failed': 'Échec du chargement',
        'no_data': 'Aucune donnée',
        'comp.select_events': 'Sélectionnez les épreuves (cliquez pour choisir)',
        'comp.current': '{source} - {count} épreuve(s) sélectionnée(s) ({type})',
        'comp.calculating': 'Calcul des classements complets, veuillez patienter...',
        'record.no_record': 'Aucun record',
        'all_cities': 'Toutes les villes de la province',
    },
    'fr-CA': {
        'nav.home': 'Accueil',
        'nav.season': 'Classements de saison',
        'nav.active': 'Classements actifs',
        'nav.region': 'Classements régionaux',
        'nav.comprehensive': 'Classements complets',
        'nav.record': 'Records régionaux',
        'filter.region': 'Région',
        'filter.project': 'Épreuve',
        'filter.gender': 'Genre',
        'filter.period': 'Période',
        'filter.province': 'Province',
        'filter.city': 'Ville',
        'filter.source': 'Type de classement',
        'filter.dataset': 'Sous-ensemble',
        'gender.all': 'Tous',
        'gender.male': 'Homme',
        'gender.female': 'Femme',
        'gender.unknown': 'Inconnu',
        'btn.single': 'Simple',
        'btn.average': 'Moyenne',
        'btn.refresh': 'Actualiser',
        'table.rank': 'Rang',
        'table.name': 'Nom',
        'table.country': 'Pays',
        'table.province': 'Province',
        'table.city': 'Ville',
        'table.result': 'Résultat',
        'table.competition': 'Compétition',
        'table.wcaid': 'ID WCA',
        'table.event': 'Épreuve',
        'table.events_count': 'Épreuves',
        'table.total_rank': 'Somme des rangs',
        'current.single': 'Simple',
        'current.average': 'Moyenne',
        'current.historical': 'Historique',
        'current.season': 'Saison',
        'current.active': 'Actif',
        'loading': 'Chargement',
        'loading_failed': 'Échec du chargement',
        'no_data': 'Aucune donnée',
        'comp.select_events': 'Sélectionnez les épreuves (cliquez pour choisir)',
        'comp.current': '{source} - {count} épreuve(s) sélectionnée(s) ({type})',
        'comp.calculating': 'Calcul des classements complets, veuillez patienter...',
        'record.no_record': 'Aucun record',
        'all_cities': 'Toutes les villes de la province',
    },
    'hr': {
        'nav.home': 'Početna',
        'nav.season': 'Sezonske ljestvice',
        'nav.active': 'Aktivne ljestvice',
        'nav.region': 'Regionalne ljestvice',
        'nav.comprehensive': 'Sveobuhvatne ljestvice',
        'nav.record': 'Regionalni rekordi',
        'filter.region': 'Regija',
        'filter.project': 'Disciplina',
        'filter.gender': 'Spol',
        'filter.period': 'Razdoblje',
        'filter.province': 'Pokrajina',
        'filter.city': 'Grad',
        'filter.source': 'Vrsta ljestvice',
        'filter.dataset': 'Podskup',
        'gender.all': 'Svi',
        'gender.male': 'Muško',
        'gender.female': 'Žensko',
        'gender.unknown': 'Nepoznato',
        'btn.single': 'Pojedinačno',
        'btn.average': 'Prosjek',
        'btn.refresh': 'Osvježi',
        'table.rank': 'Rang',
        'table.name': 'Ime',
        'table.country': 'Država',
        'table.province': 'Pokrajina',
        'table.city': 'Grad',
        'table.result': 'Rezultat',
        'table.competition': 'Natjecanje',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplina',
        'table.events_count': 'Discipline',
        'table.total_rank': 'Zbroj rangova',
        'current.single': 'Pojedinačno',
        'current.average': 'Prosjek',
        'current.historical': 'Povijesno',
        'current.season': 'Sezona',
        'current.active': 'Aktivno',
        'loading': 'Učitavanje',
        'loading_failed': 'Učitavanje nije uspjelo',
        'no_data': 'Nema podataka',
        'comp.select_events': 'Odaberite discipline (klikom odaberite)',
        'comp.current': '{source} - odabrano {count} disciplina ({type})',
        'comp.calculating': 'Izračunavam sveobuhvatne ljestvice, pričekajte...',
        'record.no_record': 'Nema rekorda',
        'all_cities': 'Svi gradovi u pokrajini',
    },
    'hu': {
        'nav.home': 'Kezdőlap',
        'nav.season': 'Szezonális ranglisták',
        'nav.active': 'Aktív ranglisták',
        'nav.region': 'Regionális ranglisták',
        'nav.comprehensive': 'Átfogó ranglisták',
        'nav.record': 'Regionális rekordok',
        'filter.region': 'Régió',
        'filter.project': 'Szám',
        'filter.gender': 'Nem',
        'filter.period': 'Időszak',
        'filter.province': 'Tartomány',
        'filter.city': 'Város',
        'filter.source': 'Ranglista típusa',
        'filter.dataset': 'Alhalmaz',
        'gender.all': 'Mind',
        'gender.male': 'Férfi',
        'gender.female': 'Nő',
        'gender.unknown': 'Ismeretlen',
        'btn.single': 'Egyéni',
        'btn.average': 'Átlag',
        'btn.refresh': 'Frissítés',
        'table.rank': 'Helyezés',
        'table.name': 'Név',
        'table.country': 'Ország',
        'table.province': 'Tartomány',
        'table.city': 'Város',
        'table.result': 'Eredmény',
        'table.competition': 'Versenysorozat',
        'table.wcaid': 'WCA azonosító',
        'table.event': 'Szám',
        'table.events_count': 'Számok',
        'table.total_rank': 'Helyezések összege',
        'current.single': 'Egyéni',
        'current.average': 'Átlag',
        'current.historical': 'Történelmi',
        'current.season': 'Szezon',
        'current.active': 'Aktív',
        'loading': 'Betöltés',
        'loading_failed': 'Sikertelen betöltés',
        'no_data': 'Nincs adat',
        'comp.select_events': 'Válasszon számokat (kattintson a választáshoz)',
        'comp.current': '{source} - {count} szám kiválasztva ({type})',
        'comp.calculating': 'Átfogó ranglista számítása, kérem várjon...',
        'record.no_record': 'Nincs rekord',
        'all_cities': 'Tartomány összes városa',
    },
    'id': {
        'nav.home': 'Beranda',
        'nav.season': 'Peringkat Musim',
        'nav.active': 'Peringkat Aktif',
        'nav.region': 'Peringkat Daerah',
        'nav.comprehensive': 'Peringkat Komprehensif',
        'nav.record': 'Rekor Daerah',
        'filter.region': 'Wilayah',
        'filter.project': 'Event',
        'filter.gender': 'Jenis Kelamin',
        'filter.period': 'Periode',
        'filter.province': 'Provinsi',
        'filter.city': 'Kota',
        'filter.source': 'Tipe Peringkat',
        'filter.dataset': 'Sub-dataset',
        'gender.all': 'Semua',
        'gender.male': 'Pria',
        'gender.female': 'Wanita',
        'gender.unknown': 'Tidak Diketahui',
        'btn.single': 'Tunggal',
        'btn.average': 'Rata-rata',
        'btn.refresh': 'Muat Ulang',
        'table.rank': 'Peringkat',
        'table.name': 'Nama',
        'table.country': 'Negara',
        'table.province': 'Provinsi',
        'table.city': 'Kota',
        'table.result': 'Hasil',
        'table.competition': 'Kompetisi',
        'table.wcaid': 'ID WCA',
        'table.event': 'Event',
        'table.events_count': 'Event',
        'table.total_rank': 'Total Peringkat',
        'current.single': 'Tunggal',
        'current.average': 'Rata-rata',
        'current.historical': 'Historis',
        'current.season': 'Musim',
        'current.active': 'Aktif',
        'loading': 'Memuat',
        'loading_failed': 'Gagal memuat data',
        'no_data': 'Tidak ada data',
        'comp.select_events': 'Pilih event (klik untuk memilih)',
        'comp.current': '{source} - {count} event dipilih ({type})',
        'comp.calculating': 'Menghitung peringkat komprehensif, harap tunggu...',
        'record.no_record': 'Tidak ada rekor',
        'all_cities': 'Semua kota di provinsi',
    },
    'it': {
        'nav.home': 'Home',
        'nav.season': 'Classifiche di Stagione',
        'nav.active': 'Classifiche Attive',
        'nav.region': 'Classifiche Regionali',
        'nav.comprehensive': 'Classifiche Complete',
        'nav.record': 'Record Regionali',
        'filter.region': 'Regione',
        'filter.project': 'Evento',
        'filter.gender': 'Genere',
        'filter.period': 'Periodo',
        'filter.province': 'Provincia',
        'filter.city': 'Città',
        'filter.source': 'Tipo di Classifica',
        'filter.dataset': 'Sottoinsieme',
        'gender.all': 'Tutti',
        'gender.male': 'Uomo',
        'gender.female': 'Donna',
        'gender.unknown': 'Sconosciuto',
        'btn.single': 'Singolo',
        'btn.average': 'Media',
        'btn.refresh': 'Aggiorna',
        'table.rank': 'Posizione',
        'table.name': 'Nome',
        'table.country': 'Paese',
        'table.province': 'Provincia',
        'table.city': 'Città',
        'table.result': 'Risultato',
        'table.competition': 'Gara',
        'table.wcaid': 'ID WCA',
        'table.event': 'Evento',
        'table.events_count': 'Eventi',
        'table.total_rank': 'Somma Posizioni',
        'current.single': 'Singolo',
        'current.average': 'Media',
        'current.historical': 'Storico',
        'current.season': 'Stagione',
        'current.active': 'Attivo',
        'loading': 'Caricamento',
        'loading_failed': 'Caricamento fallito',
        'no_data': 'Nessun dato',
        'comp.select_events': 'Seleziona eventi (clicca per scegliere)',
        'comp.current': '{source} - {count} evento/i selezionato/i ({type})',
        'comp.calculating': 'Calcolo classifiche complete, attendere...',
        'record.no_record': 'Nessun record',
        'all_cities': 'Tutte le città della provincia',
    },
    'ja': {
        'nav.home': 'ホーム',
        'nav.season': 'シーズンランキング',
        'nav.active': 'アクティブランキング',
        'nav.region': '地域別ランキング',
        'nav.comprehensive': '総合ランキング',
        'nav.record': '地域記録',
        'filter.region': '地域',
        'filter.project': '種目',
        'filter.gender': '性別',
        'filter.period': '期間',
        'filter.province': '省/市',
        'filter.city': '都市',
        'filter.source': 'ランキングタイプ',
        'filter.dataset': 'サブデータセット',
        'gender.all': 'すべて',
        'gender.male': '男性',
        'gender.female': '女性',
        'gender.unknown': '不明',
        'btn.single': '単発',
        'btn.average': '平均',
        'btn.refresh': '更新',
        'table.rank': '順位',
        'table.name': '名前',
        'table.country': '国',
        'table.province': '省/市',
        'table.city': '都市',
        'table.result': '記録',
        'table.competition': '大会',
        'table.wcaid': 'WCA ID',
        'table.event': '種目',
        'table.events_count': '種目数',
        'table.total_rank': '順位合計',
        'current.single': '単発',
        'current.average': '平均',
        'current.historical': '歴代',
        'current.season': 'シーズン',
        'current.active': 'アクティブ',
        'loading': '読み込み中',
        'loading_failed': 'データ読み込み失敗',
        'no_data': 'データなし',
        'comp.select_events': '種目を選択（クリックで選択）',
        'comp.current': '{source} - {count}種目選択 ({type})',
        'comp.calculating': '総合ランキング計算中、お待ちください...',
        'record.no_record': '記録なし',
        'all_cities': '省内全都市',
    },
    'kk': {
        'nav.home': 'Басты бет',
        'nav.season': 'Маусымдық рейтингтер',
        'nav.active': 'Белсенді рейтингтер',
        'nav.region': 'Аймақтық рейтингтер',
        'nav.comprehensive': 'Жан-жақты рейтингтер',
        'nav.record': 'Аймақтық рекордтар',
        'filter.region': 'Аймақ',
        'filter.project': 'Пән',
        'filter.gender': 'Жыныс',
        'filter.period': 'Кезең',
        'filter.province': 'Облыс',
        'filter.city': 'Қала',
        'filter.source': 'Рейтинг түрі',
        'filter.dataset': 'Ішкі жиынтық',
        'gender.all': 'Барлығы',
        'gender.male': 'Ер',
        'gender.female': 'Әйел',
        'gender.unknown': 'Белгісіз',
        'btn.single': 'Жеке',
        'btn.average': 'Орташа',
        'btn.refresh': 'Жаңарту',
        'table.rank': 'Орын',
        'table.name': 'Аты',
        'table.country': 'Ел',
        'table.province': 'Облыс',
        'table.city': 'Қала',
        'table.result': 'Нәтиже',
        'table.competition': 'Жарыс',
        'table.wcaid': 'WCA ID',
        'table.event': 'Пән',
        'table.events_count': 'Пәндер',
        'table.total_rank': 'Орындар қосындысы',
        'current.single': 'Жеке',
        'current.average': 'Орташа',
        'current.historical': 'Тарихи',
        'current.season': 'Маусым',
        'current.active': 'Белсенді',
        'loading': 'Жүктелуде',
        'loading_failed': 'Деректерді жүктеу сәтсіз',
        'no_data': 'Деректер жоқ',
        'comp.select_events': 'Пәндерді таңдаңыз (таңдау үшін басыңыз)',
        'comp.current': '{source} - {count} пән таңдалды ({type})',
        'comp.calculating': 'Жан-жақты рейтингтер есептелуде, күте тұрыңыз...',
        'record.no_record': 'Рекорд жоқ',
        'all_cities': 'Облыстағы барлық қалалар',
    },
    'ko': {
        'nav.home': '홈',
        'nav.season': '시즌 랭킹',
        'nav.active': '활동 랭킹',
        'nav.region': '지역 랭킹',
        'nav.comprehensive': '종합 랭킹',
        'nav.record': '지역 기록',
        'filter.region': '지역',
        'filter.project': '종목',
        'filter.gender': '성별',
        'filter.period': '기간',
        'filter.province': '성/시',
        'filter.city': '도시',
        'filter.source': '랭킹 유형',
        'filter.dataset': '하위 데이터셋',
        'gender.all': '전체',
        'gender.male': '남성',
        'gender.female': '여성',
        'gender.unknown': '알 수 없음',
        'btn.single': '싱글',
        'btn.average': '평균',
        'btn.refresh': '새로고침',
        'table.rank': '순위',
        'table.name': '이름',
        'table.country': '국가',
        'table.province': '성/시',
        'table.city': '도시',
        'table.result': '기록',
        'table.competition': '대회',
        'table.wcaid': 'WCA ID',
        'table.event': '종목',
        'table.events_count': '종목 수',
        'table.total_rank': '순위 합계',
        'current.single': '싱글',
        'current.average': '평균',
        'current.historical': '역사',
        'current.season': '시즌',
        'current.active': '활동',
        'loading': '로딩 중',
        'loading_failed': '데이터 로딩 실패',
        'no_data': '데이터 없음',
        'comp.select_events': '종목 선택 (클릭하여 선택)',
        'comp.current': '{source} - {count}개 종목 선택됨 ({type})',
        'comp.calculating': '종합 랭킹 계산 중, 잠시만 기다려주세요...',
        'record.no_record': '기록 없음',
        'all_cities': '성/시 내 모든 도시',
    },
    'nl': {
        'nav.home': 'Home',
        'nav.season': 'Seizoensranglijsten',
        'nav.active': 'Actieve ranglijsten',
        'nav.region': 'Regionale ranglijsten',
        'nav.comprehensive': 'Uitgebreide ranglijsten',
        'nav.record': 'Regionale records',
        'filter.region': 'Regio',
        'filter.project': 'Onderdeel',
        'filter.gender': 'Geslacht',
        'filter.period': 'Periode',
        'filter.province': 'Provincie',
        'filter.city': 'Stad',
        'filter.source': 'Ranglijsttype',
        'filter.dataset': 'Subdataset',
        'gender.all': 'Alle',
        'gender.male': 'Man',
        'gender.female': 'Vrouw',
        'gender.unknown': 'Onbekend',
        'btn.single': 'Enkel',
        'btn.average': 'Gemiddelde',
        'btn.refresh': 'Vernieuwen',
        'table.rank': 'Plaats',
        'table.name': 'Naam',
        'table.country': 'Land',
        'table.province': 'Provincie',
        'table.city': 'Stad',
        'table.result': 'Resultaat',
        'table.competition': 'Wedstrijd',
        'table.wcaid': 'WCA ID',
        'table.event': 'Onderdeel',
        'table.events_count': 'Onderdelen',
        'table.total_rank': 'Totaal plaats',
        'current.single': 'Enkel',
        'current.average': 'Gemiddelde',
        'current.historical': 'Historisch',
        'current.season': 'Seizoen',
        'current.active': 'Actief',
        'loading': 'Laden',
        'loading_failed': 'Gegevens laden mislukt',
        'no_data': 'Geen gegevens',
        'comp.select_events': 'Selecteer onderdelen (klik om te kiezen)',
        'comp.current': '{source} - {count} onderde(e)l(en) geselecteerd ({type})',
        'comp.calculating': 'Uitgebreide ranglijsten berekenen, even geduld...',
        'record.no_record': 'Geen record',
        'all_cities': 'Alle steden in de provincie',
    },
    'pl': {
        'nav.home': 'Strona główna',
        'nav.season': 'Rankingi sezonowe',
        'nav.active': 'Rankingi aktywnych',
        'nav.region': 'Rankingi regionalne',
        'nav.comprehensive': 'Rankingi kompleksowe',
        'nav.record': 'Rekordy regionalne',
        'filter.region': 'Region',
        'filter.project': 'Konkurencja',
        'filter.gender': 'Płeć',
        'filter.period': 'Okres',
        'filter.province': 'Województwo',
        'filter.city': 'Miasto',
        'filter.source': 'Typ rankingu',
        'filter.dataset': 'Podzbiór',
        'gender.all': 'Wszyscy',
        'gender.male': 'Mężczyzna',
        'gender.female': 'Kobieta',
        'gender.unknown': 'Nieznana',
        'btn.single': 'Pojedynczy',
        'btn.average': 'Średnia',
        'btn.refresh': 'Odśwież',
        'table.rank': 'Miejsce',
        'table.name': 'Imię i nazwisko',
        'table.country': 'Kraj',
        'table.province': 'Województwo',
        'table.city': 'Miasto',
        'table.result': 'Wynik',
        'table.competition': 'Zawody',
        'table.wcaid': 'ID WCA',
        'table.event': 'Konkurencja',
        'table.events_count': 'Konkurencje',
        'table.total_rank': 'Suma miejsc',
        'current.single': 'Pojedynczy',
        'current.average': 'Średnia',
        'current.historical': 'Historyczny',
        'current.season': 'Sezon',
        'current.active': 'Aktywny',
        'loading': 'Ładowanie',
        'loading_failed': 'Nie udało się załadować danych',
        'no_data': 'Brak danych',
        'comp.select_events': 'Wybierz konkurencje (kliknij, aby wybrać)',
        'comp.current': '{source} - wybrano {count} konkurencji ({type})',
        'comp.calculating': 'Obliczanie rankingów kompleksowych, proszę czekać...',
        'record.no_record': 'Brak rekordu',
        'all_cities': 'Wszystkie miasta w województwie',
    },
    'pt-PT': {
        'nav.home': 'Início',
        'nav.season': 'Classificações de Temporada',
        'nav.active': 'Classificações Ativas',
        'nav.region': 'Classificações Regionais',
        'nav.comprehensive': 'Classificações Abrangentes',
        'nav.record': 'Recordes Regionais',
        'filter.region': 'Região',
        'filter.project': 'Evento',
        'filter.gender': 'Género',
        'filter.period': 'Período',
        'filter.province': 'Província',
        'filter.city': 'Cidade',
        'filter.source': 'Tipo de Classificação',
        'filter.dataset': 'Subconjunto',
        'gender.all': 'Todos',
        'gender.male': 'Masculino',
        'gender.female': 'Feminino',
        'gender.unknown': 'Desconhecido',
        'btn.single': 'Simples',
        'btn.average': 'Média',
        'btn.refresh': 'Atualizar',
        'table.rank': 'Posição',
        'table.name': 'Nome',
        'table.country': 'País',
        'table.province': 'Província',
        'table.city': 'Cidade',
        'table.result': 'Resultado',
        'table.competition': 'Competição',
        'table.wcaid': 'ID WCA',
        'table.event': 'Evento',
        'table.events_count': 'Eventos',
        'table.total_rank': 'Soma de Posições',
        'current.single': 'Simples',
        'current.average': 'Média',
        'current.historical': 'Histórico',
        'current.season': 'Temporada',
        'current.active': 'Ativo',
        'loading': 'A carregar',
        'loading_failed': 'Falha ao carregar dados',
        'no_data': 'Sem dados',
        'comp.select_events': 'Selecione eventos (clique para escolher)',
        'comp.current': '{source} - {count} evento(s) selecionado(s) ({type})',
        'comp.calculating': 'A calcular classificações abrangentes, aguarde...',
        'record.no_record': 'Sem recorde',
        'all_cities': 'Todas as cidades da província',
    },
    'pt-BR': {
        'nav.home': 'Início',
        'nav.season': 'Rankings de Temporada',
        'nav.active': 'Rankings Ativos',
        'nav.region': 'Rankings Regionais',
        'nav.comprehensive': 'Rankings Abrangentes',
        'nav.record': 'Recordes Regionais',
        'filter.region': 'Região',
        'filter.project': 'Evento',
        'filter.gender': 'Gênero',
        'filter.period': 'Período',
        'filter.province': 'Província',
        'filter.city': 'Cidade',
        'filter.source': 'Tipo de Ranking',
        'filter.dataset': 'Subconjunto',
        'gender.all': 'Todos',
        'gender.male': 'Homem',
        'gender.female': 'Mulher',
        'gender.unknown': 'Desconhecido',
        'btn.single': 'Simples',
        'btn.average': 'Média',
        'btn.refresh': 'Atualizar',
        'table.rank': 'Posição',
        'table.name': 'Nome',
        'table.country': 'País',
        'table.province': 'Província',
        'table.city': 'Cidade',
        'table.result': 'Resultado',
        'table.competition': 'Competição',
        'table.wcaid': 'ID WCA',
        'table.event': 'Evento',
        'table.events_count': 'Eventos',
        'table.total_rank': 'Soma de Posições',
        'current.single': 'Simples',
        'current.average': 'Média',
        'current.historical': 'Histórico',
        'current.season': 'Temporada',
        'current.active': 'Ativo',
        'loading': 'Carregando',
        'loading_failed': 'Falha ao carregar dados',
        'no_data': 'Sem dados',
        'comp.select_events': 'Selecione eventos (clique para escolher)',
        'comp.current': '{source} - {count} evento(s) selecionado(s) ({type})',
        'comp.calculating': 'Calculando rankings abrangentes, aguarde...',
        'record.no_record': 'Sem recorde',
        'all_cities': 'Todas as cidades da província',
    },
    'ro': {
        'nav.home': 'Acasă',
        'nav.season': 'Clasamente Sezoniere',
        'nav.active': 'Clasamente Active',
        'nav.region': 'Clasamente Regionale',
        'nav.comprehensive': 'Clasamente Complete',
        'nav.record': 'Recorduri Regionale',
        'filter.region': 'Regiune',
        'filter.project': 'Probă',
        'filter.gender': 'Gen',
        'filter.period': 'Perioadă',
        'filter.province': 'Provincie',
        'filter.city': 'Oraș',
        'filter.source': 'Tip Clasament',
        'filter.dataset': 'Subset',
        'gender.all': 'Toți',
        'gender.male': 'Bărbat',
        'gender.female': 'Femeie',
        'gender.unknown': 'Necunoscut',
        'btn.single': 'Simplu',
        'btn.average': 'Medie',
        'btn.refresh': 'Reîmprospătare',
        'table.rank': 'Loc',
        'table.name': 'Nume',
        'table.country': 'Țară',
        'table.province': 'Provincie',
        'table.city': 'Oraș',
        'table.result': 'Rezultat',
        'table.competition': 'Competiție',
        'table.wcaid': 'ID WCA',
        'table.event': 'Probă',
        'table.events_count': 'Probe',
        'table.total_rank': 'Suma Locurilor',
        'current.single': 'Simplu',
        'current.average': 'Medie',
        'current.historical': 'Istoric',
        'current.season': 'Sezon',
        'current.active': 'Activ',
        'loading': 'Se încarcă',
        'loading_failed': 'Încărcarea datelor a eșuat',
        'no_data': 'Nu există date',
        'comp.select_events': 'Selectați probe (click pentru a alege)',
        'comp.current': '{source} - {count} probă(e) selectată(e) ({type})',
        'comp.calculating': 'Se calculează clasamentele complete, vă rugăm așteptați...',
        'record.no_record': 'Niciun record',
        'all_cities': 'Toate orașele din provincie',
    },
    'ru': {
        'nav.home': 'Главная',
        'nav.season': 'Сезонные рейтинги',
        'nav.active': 'Активные рейтинги',
        'nav.region': 'Региональные рейтинги',
        'nav.comprehensive': 'Комплексные рейтинги',
        'nav.record': 'Региональные рекорды',
        'filter.region': 'Регион',
        'filter.project': 'Дисциплина',
        'filter.gender': 'Пол',
        'filter.period': 'Период',
        'filter.province': 'Провинция',
        'filter.city': 'Город',
        'filter.source': 'Тип рейтинга',
        'filter.dataset': 'Поднабор',
        'gender.all': 'Все',
        'gender.male': 'Мужской',
        'gender.female': 'Женский',
        'gender.unknown': 'Неизвестно',
        'btn.single': 'Сингл',
        'btn.average': 'Среднее',
        'btn.refresh': 'Обновить',
        'table.rank': 'Место',
        'table.name': 'Имя',
        'table.country': 'Страна',
        'table.province': 'Провинция',
        'table.city': 'Город',
        'table.result': 'Результат',
        'table.competition': 'Соревнование',
        'table.wcaid': 'WCA ID',
        'table.event': 'Дисциплина',
        'table.events_count': 'Дисциплины',
        'table.total_rank': 'Сумма мест',
        'current.single': 'Сингл',
        'current.average': 'Среднее',
        'current.historical': 'Исторический',
        'current.season': 'Сезон',
        'current.active': 'Активный',
        'loading': 'Загрузка',
        'loading_failed': 'Ошибка загрузки данных',
        'no_data': 'Нет данных',
        'comp.select_events': 'Выберите дисциплины (нажмите для выбора)',
        'comp.current': '{source} - выбрано {count} дисциплин ({type})',
        'comp.calculating': 'Расчет комплексных рейтингов, пожалуйста, подождите...',
        'record.no_record': 'Нет рекорда',
        'all_cities': 'Все города провинции',
    },
    'sk': {
        'nav.home': 'Domov',
        'nav.season': 'Sezónne rebríčky',
        'nav.active': 'Aktívne rebríčky',
        'nav.region': 'Regionálne rebríčky',
        'nav.comprehensive': 'Komplexné rebríčky',
        'nav.record': 'Regionálne rekordy',
        'filter.region': 'Región',
        'filter.project': 'Disciplína',
        'filter.gender': 'Pohlavie',
        'filter.period': 'Obdobie',
        'filter.province': 'Provincia',
        'filter.city': 'Mesto',
        'filter.source': 'Typ rebríčka',
        'filter.dataset': 'Podmnožina',
        'gender.all': 'Všetky',
        'gender.male': 'Muž',
        'gender.female': 'Žena',
        'gender.unknown': 'Neznáme',
        'btn.single': 'Jednotlivo',
        'btn.average': 'Priemer',
        'btn.refresh': 'Obnoviť',
        'table.rank': 'Poradie',
        'table.name': 'Meno',
        'table.country': 'Krajina',
        'table.province': 'Provincia',
        'table.city': 'Mesto',
        'table.result': 'Výsledok',
        'table.competition': 'Súťaž',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplína',
        'table.events_count': 'Disciplíny',
        'table.total_rank': 'Súčet poradí',
        'current.single': 'Jednotlivo',
        'current.average': 'Priemer',
        'current.historical': 'Historický',
        'current.season': 'Sezóna',
        'current.active': 'Aktívny',
        'loading': 'Načítava sa',
        'loading_failed': 'Načítanie zlyhalo',
        'no_data': 'Žiadne údaje',
        'comp.select_events': 'Vyberte disciplíny (kliknutím vyberiete)',
        'comp.current': '{source} - vybraných {count} disciplín ({type})',
        'comp.calculating': 'Prebieha výpočet komplexných rebríčkov, čakajte prosím...',
        'record.no_record': 'Žiadny rekord',
        'all_cities': 'Všetky mestá v provincii',
    },
    'sl': {
        'nav.home': 'Domov',
        'nav.season': 'Sezonske lestvice',
        'nav.active': 'Aktivne lestvice',
        'nav.region': 'Regionalne lestvice',
        'nav.comprehensive': 'Celostne lestvice',
        'nav.record': 'Regionalni rekordi',
        'filter.region': 'Regija',
        'filter.project': 'Disciplina',
        'filter.gender': 'Spol',
        'filter.period': 'Obdobje',
        'filter.province': 'Provinca',
        'filter.city': 'Mesto',
        'filter.source': 'Vrsta lestvice',
        'filter.dataset': 'Podmnožica',
        'gender.all': 'Vsi',
        'gender.male': 'Moški',
        'gender.female': 'Ženska',
        'gender.unknown': 'Neznano',
        'btn.single': 'Posamezno',
        'btn.average': 'Povprečje',
        'btn.refresh': 'Osveži',
        'table.rank': 'Uvrstitev',
        'table.name': 'Ime',
        'table.country': 'Država',
        'table.province': 'Provinca',
        'table.city': 'Mesto',
        'table.result': 'Rezultat',
        'table.competition': 'Tekmovanje',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplina',
        'table.events_count': 'Discipline',
        'table.total_rank': 'Skupna uvrstitev',
        'current.single': 'Posamezno',
        'current.average': 'Povprečje',
        'current.historical': 'Zgodovinsko',
        'current.season': 'Sezona',
        'current.active': 'Aktivno',
        'loading': 'Nalaganje',
        'loading_failed': 'Nalaganje podatkov ni uspelo',
        'no_data': 'Ni podatkov',
        'comp.select_events': 'Izberite discipline (kliknite za izbiro)',
        'comp.current': '{source} - izbranih {count} disciplin ({type})',
        'comp.calculating': 'Izračunavam celostne lestvice, prosimo počakajte...',
        'record.no_record': 'Ni rekorda',
        'all_cities': 'Vsa mesta v provinci',
    },
    'sv': {
        'nav.home': 'Hem',
        'nav.season': 'Säsongsranking',
        'nav.active': 'Aktiv ranking',
        'nav.region': 'Regional ranking',
        'nav.comprehensive': 'Omfattande ranking',
        'nav.record': 'Regionala rekord',
        'filter.region': 'Region',
        'filter.project': 'Gren',
        'filter.gender': 'Kön',
        'filter.period': 'Period',
        'filter.province': 'Provins',
        'filter.city': 'Stad',
        'filter.source': 'Rankingtyp',
        'filter.dataset': 'Delmängd',
        'gender.all': 'Alla',
        'gender.male': 'Man',
        'gender.female': 'Kvinna',
        'gender.unknown': 'Okänd',
        'btn.single': 'Singel',
        'btn.average': 'Medel',
        'btn.refresh': 'Uppdatera',
        'table.rank': 'Placering',
        'table.name': 'Namn',
        'table.country': 'Land',
        'table.province': 'Provins',
        'table.city': 'Stad',
        'table.result': 'Resultat',
        'table.competition': 'Tävling',
        'table.wcaid': 'WCA ID',
        'table.event': 'Gren',
        'table.events_count': 'Grenar',
        'table.total_rank': 'Total placering',
        'current.single': 'Singel',
        'current.average': 'Medel',
        'current.historical': 'Historisk',
        'current.season': 'Säsong',
        'current.active': 'Aktiv',
        'loading': 'Laddar',
        'loading_failed': 'Data kunde inte laddas',
        'no_data': 'Ingen data',
        'comp.select_events': 'Välj grenar (klicka för att välja)',
        'comp.current': '{source} - {count} gren(ar) valda ({type})',
        'comp.calculating': 'Beräknar omfattande ranking, vänligen vänta...',
        'record.no_record': 'Inget rekord',
        'all_cities': 'Alla städer i provinsen',
    },
    'th': {
        'nav.home': 'หน้าแรก',
        'nav.season': 'อันดับประจำฤดูกาล',
        'nav.active': 'อันดับปัจจุบัน',
        'nav.region': 'อันดับภูมิภาค',
        'nav.comprehensive': 'อันดับรวม',
        'nav.record': 'สถิติภูมิภาค',
        'filter.region': 'ภูมิภาค',
        'filter.project': 'ประเภท',
        'filter.gender': 'เพศ',
        'filter.period': 'ช่วงเวลา',
        'filter.province': 'จังหวัด',
        'filter.city': 'เมือง',
        'filter.source': 'ประเภทอันดับ',
        'filter.dataset': 'ชุดข้อมูลย่อย',
        'gender.all': 'ทั้งหมด',
        'gender.male': 'ชาย',
        'gender.female': 'หญิง',
        'gender.unknown': 'ไม่ทราบ',
        'btn.single': 'ครั้งเดียว',
        'btn.average': 'ค่าเฉลี่ย',
        'btn.refresh': 'รีเฟรช',
        'table.rank': 'อันดับ',
        'table.name': 'ชื่อ',
        'table.country': 'ประเทศ',
        'table.province': 'จังหวัด',
        'table.city': 'เมือง',
        'table.result': 'ผลลัพธ์',
        'table.competition': 'การแข่งขัน',
        'table.wcaid': 'WCA ID',
        'table.event': 'ประเภท',
        'table.events_count': 'ประเภท',
        'table.total_rank': 'ผลรวมอันดับ',
        'current.single': 'ครั้งเดียว',
        'current.average': 'ค่าเฉลี่ย',
        'current.historical': 'ประวัติศาสตร์',
        'current.season': 'ฤดูกาล',
        'current.active': 'ปัจจุบัน',
        'loading': 'กำลังโหลด',
        'loading_failed': 'โหลดข้อมูลล้มเหลว',
        'no_data': 'ไม่มีข้อมูล',
        'comp.select_events': 'เลือกประเภท (คลิกเพื่อเลือก)',
        'comp.current': '{source} - เลือก {count} ประเภท ({type})',
        'comp.calculating': 'กำลังคำนวณอันดับรวม โปรดรอ...',
        'record.no_record': 'ไม่มีสถิติ',
        'all_cities': 'ทุกเมืองในจังหวัด',
    },
    'uk': {
        'nav.home': 'Головна',
        'nav.season': 'Сезонні рейтинги',
        'nav.active': 'Активні рейтинги',
        'nav.region': 'Регіональні рейтинги',
        'nav.comprehensive': 'Комплексні рейтинги',
        'nav.record': 'Регіональні рекорди',
        'filter.region': 'Регіон',
        'filter.project': 'Дисципліна',
        'filter.gender': 'Стать',
        'filter.period': 'Період',
        'filter.province': 'Провінція',
        'filter.city': 'Місто',
        'filter.source': 'Тип рейтингу',
        'filter.dataset': 'Піднабір',
        'gender.all': 'Усі',
        'gender.male': 'Чоловік',
        'gender.female': 'Жінка',
        'gender.unknown': 'Невідомо',
        'btn.single': 'Сингл',
        'btn.average': 'Середнє',
        'btn.refresh': 'Оновити',
        'table.rank': 'Місце',
        'table.name': 'Ім\'я',
        'table.country': 'Країна',
        'table.province': 'Провінція',
        'table.city': 'Місто',
        'table.result': 'Результат',
        'table.competition': 'Змагання',
        'table.wcaid': 'WCA ID',
        'table.event': 'Дисципліна',
        'table.events_count': 'Дисципліни',
        'table.total_rank': 'Сума місць',
        'current.single': 'Сингл',
        'current.average': 'Середнє',
        'current.historical': 'Історичний',
        'current.season': 'Сезон',
        'current.active': 'Активний',
        'loading': 'Завантаження',
        'loading_failed': 'Не вдалося завантажити дані',
        'no_data': 'Немає даних',
        'comp.select_events': 'Виберіть дисципліни (натисніть для вибору)',
        'comp.current': '{source} - вибрано {count} дисциплін ({type})',
        'comp.calculating': 'Розрахунок комплексних рейтингів, зачекайте...',
        'record.no_record': 'Немає рекорду',
        'all_cities': 'Усі міста провінції',
    },
    'vi': {
        'nav.home': 'Trang chủ',
        'nav.season': 'Xếp hạng theo mùa',
        'nav.active': 'Xếp hạng hiện tại',
        'nav.region': 'Xếp hạng khu vực',
        'nav.comprehensive': 'Xếp hạng tổng hợp',
        'nav.record': 'Kỷ lục khu vực',
        'filter.region': 'Khu vực',
        'filter.project': 'Nội dung',
        'filter.gender': 'Giới tính',
        'filter.period': 'Giai đoạn',
        'filter.province': 'Tỉnh',
        'filter.city': 'Thành phố',
        'filter.source': 'Loại xếp hạng',
        'filter.dataset': 'Tập dữ liệu con',
        'gender.all': 'Tất cả',
        'gender.male': 'Nam',
        'gender.female': 'Nữ',
        'gender.unknown': 'Không xác định',
        'btn.single': 'Đơn lẻ',
        'btn.average': 'Trung bình',
        'btn.refresh': 'Làm mới',
        'table.rank': 'Hạng',
        'table.name': 'Tên',
        'table.country': 'Quốc gia',
        'table.province': 'Tỉnh',
        'table.city': 'Thành phố',
        'table.result': 'Kết quả',
        'table.competition': 'Cuộc thi',
        'table.wcaid': 'ID WCA',
        'table.event': 'Nội dung',
        'table.events_count': 'Số nội dung',
        'table.total_rank': 'Tổng hạng',
        'current.single': 'Đơn lẻ',
        'current.average': 'Trung bình',
        'current.historical': 'Lịch sử',
        'current.season': 'Mùa',
        'current.active': 'Hiện tại',
        'loading': 'Đang tải',
        'loading_failed': 'Tải dữ liệu thất bại',
        'no_data': 'Không có dữ liệu',
        'comp.select_events': 'Chọn nội dung (nhấp để chọn)',
        'comp.current': '{source} - đã chọn {count} nội dung ({type})',
        'comp.calculating': 'Đang tính xếp hạng tổng hợp, vui lòng đợi...',
        'record.no_record': 'Không có kỷ lục',
        'all_cities': 'Tất cả thành phố trong tỉnh',
    }
};

// 翻译辅助函数（全局可用）
window.__ = function(key, params = {}) {
    const lang = state.currentLang;
    const translations = TRANSLATIONS[lang] || TRANSLATIONS['en'] || {};
    let text = translations[key];
    if (text === undefined) {
        // 回退到英文
        text = TRANSLATIONS['en']?.[key] || key;
    }
    // 简单替换参数 {param}
    if (params) {
        for (let [k, v] of Object.entries(params)) {
            text = text.replace(new RegExp(`\\{${k}\\}`, 'g'), v);
        }
    }
    return text;
};