// 支持的语言列表（用于下拉框）
window.LANG_LIST = [
    { code: 'en', name: 'English' },
    { code: 'ca', name: 'Català' },
    { code: 'cs', name: 'Čeština' },
    { code: 'da', name: 'Dansk' },
    { code: 'de', name: 'Deutsch' },
    { code: 'eo', name: 'Esperanto' },
    { code: 'es-ES', name: 'Español (España)' },
    { code: 'es-419', name: 'Español (América Latina)' },
    { code: 'eu', name: 'Euskara' },
    { code: 'fi', name: 'Suomi' },
    { code: 'fr', name: 'Français' },
    { code: 'fr-CA', name: 'Français Canadien' },
    { code: 'hr', name: 'Hrvatski' },
    { code: 'hu', name: 'Magyar' },
    { code: 'id', name: 'Bahasa Indonesia' },
    { code: 'it', name: 'Italiano' },
    { code: 'ja', name: '日本語' },
    { code: 'kk', name: 'Қазақша' },
    { code: 'ko', name: '한국어' },
    { code: 'nl', name: 'Nederlands' },
    { code: 'pl', name: 'Polski' },
    { code: 'pt-PT', name: 'Português Europeu' },
    { code: 'pt-BR', name: 'Português Brasileiro' },
    { code: 'ro', name: 'Română' },
    { code: 'ru', name: 'Русский' },
    { code: 'sk', name: 'Slovenský' },
    { code: 'sl', name: 'Slovenščina' },
    { code: 'sv', name: 'Svenska' },
    { code: 'th', name: 'ภาษาไทย' },
    { code: 'uk', name: 'Українська' },
    { code: 'vi', name: 'Tiếng Việt' },
    { code: 'zh-CN', name: '简体中文' },
    { code: 'zh-TW', name: '繁體中文' }
];

// 翻译资源 (key: 语言代码, value: 翻译对象)
// 未提供的键将自动回退到英文 (en)
window.TRANSLATIONS = {
    // 英文（完整）
    'en': {
        'nav.home': 'Home',
        'nav.season': 'Season Rankings',
        'nav.active': 'Active Rankings',
        'nav.region': 'Regional Rankings',
        'nav.comprehensive': 'Comprehensive Rankings',
        'nav.record': 'Regional Records',
        'season.title': 'Season Rankings',
        'season.subtitle': 'This page shows season rankings, taking one year as a cycle (e.g., 2026 season). It ranks players\' best results in the current season to reflect their highest competitive level. All ranking results are from official WCA competitions.',
        'active.title': 'Active Rankings',
        'active.subtitle': 'This page shows active rankings, taking three years as a period. It ranks players\' best results in the last three years to reflect their recent competitive level. Players with no competition records for more than three years are not included. All ranking results are from official WCA competitions.',
        'region.title': 'Regional Rankings',
        'region.subtitle': 'This page shows rankings of Chinese players within their provinces/cities. For players who did not select their region on Cubing China before May 2018, they are automatically assigned to the fictional "Shenshou Valley" (see homepage announcement for details). All ranking results are from official WCA competitions.',
        'comprehensive.title': 'Comprehensive Rankings',
        'comprehensive.subtitle': 'This page calculates the sum of ranks across multiple events and ranks players accordingly.',
        'record.title': 'Regional Records',
        'record.subtitle': 'This page shows records for all provinces and cities in China across all WCA events. All results are from official WCA rankings.',
        'filter.region': 'Region',
        'filter.project': 'Event',
        'filter.gender': 'Gender',
        'filter.period': 'Period',
        'filter.province': 'Province',
        'filter.city': 'City',
        'filter.source': 'Ranking Type',
        'filter.dataset': 'Sub-dataset',
        'gender.all': 'All',
        'gender.male': 'Male',
        'gender.female': 'Female',
        'gender.unknown': 'Unknown',
        'btn.single': 'Single',
        'btn.average': 'Average',
        'btn.refresh': 'Refresh',
        'table.rank': 'Rank',
        'table.name': 'Name',
        'table.country': 'Country',
        'table.province': 'Province',
        'table.city': 'City',
        'table.result': 'Result',
        'table.competition': 'Competition',
        'table.wcaid': 'WCA ID',
        'table.event': 'Event',
        'table.events_count': 'Events',
        'table.total_rank': 'Total Rank',
        'current.single': 'Single',
        'current.average': 'Average',
        'current.historical': 'Historical',
        'current.season': 'Season',
        'current.active': 'Active',
        'loading': 'Loading',
        'loading_failed': 'Data loading failed',
        'no_data': 'No data',
        'announcement.region.title': 'About Regional Information',
        'announcement.region.content': 'Since May 2018, Cubing China has stopped displaying players\' cities. Players without city information after that date are assigned to the fictional "Shenshou Valley" by the author. The current province/city data comes from data crawled by 魔友赵吉波 before the cancellation. Many thanks to him!',
        'announcement.launch.title': 'Website Launch',
        'announcement.launch.content': 'XCUBING website is now online. It provides season rankings, active rankings, regional rankings, comprehensive rankings, and regional records from WCA events. We welcome all cubers to experience the site and provide feedback on any issues or suggestions. If you encounter any errors, please contact the author at: xcubing@qq.com.',
        'comp.select_events': 'Select events (click to choose)',
        'comp.current': '{source} - {count} event(s) selected ({type})',
        'comp.calculating': 'Calculating comprehensive rankings, please wait...',
        'record.no_record': 'No record',
        'all_cities': 'All cities in province',
    },

    // 简体中文（完整）
    'zh-CN': {
        'nav.home': '首页',
        'nav.season': '赛季排名',
        'nav.active': '现役排名',
        'nav.region': '省市排名',
        'nav.comprehensive': '综合排名',
        'nav.record': '省市纪录',
        'season.title': '赛季排名',
        'season.subtitle': '本页面为赛季排名，以一年为一个周期（如2026年即为2026赛季），将参赛选手在这个赛季的最佳成绩进行排名，以反映他们在当前赛季的最高竞技水平。所有的排名成绩源自WCA赛事的官方排名。',
        'active.title': '现役排名',
        'active.subtitle': '本页面为现役排名，以三年为期，将参赛选手在此期间的最佳成绩进行排名，以反映他们在最近三年的最高竞技水平，超过三年无参赛记录的选手不被列入排名。所有的排名成绩源自WCA赛事的官方排名。',
        'region.title': '省市排名',
        'region.subtitle': '本页面为省市排名，可以查看中国选手在其归属地的排名，对于截至2018年5月前没有在粗饼网选择归属地的选手，系统将自动将其归入本站虚构的秘境——神手谷（具体缘由详见首页公告）。所有的排名成绩源自WCA赛事的官方排名。',
        'comprehensive.title': '综合排名',
        'comprehensive.subtitle': '本页面为综合排名，可计算选手在多个项目的排名总和并进行排名。',
        'record.title': '省市纪录',
        'record.subtitle': '本页面为省市纪录，可以查看中国所有有参赛选手的省份及城市在WCA所有项目的纪录。所有的成绩源自WCA官方排名。',
        'filter.region': '地区',
        'filter.project': '项目',
        'filter.gender': '性别',
        'filter.period': '时期',
        'filter.province': '省份',
        'filter.city': '城市',
        'filter.source': '排名类型',
        'filter.dataset': '时期',
        'gender.all': '所有',
        'gender.male': '男',
        'gender.female': '女',
        'gender.unknown': '未知',
        'btn.single': '单次',
        'btn.average': '平均',
        'btn.refresh': '刷新',
        'table.rank': '排名',
        'table.name': '姓名',
        'table.country': '国家',
        'table.province': '省份',
        'table.city': '城市',
        'table.result': '成绩',
        'table.competition': '比赛',
        'table.wcaid': 'WCA ID',
        'table.event': '项目',
        'table.events_count': '参与项目数',
        'table.total_rank': '排名总和',
        'current.single': '单次',
        'current.average': '平均',
        'current.historical': '历史',
        'current.season': '赛季',
        'current.active': '现役',
        'loading': '加载中',
        'loading_failed': '数据加载失败',
        'no_data': '暂无数据',
        'announcement.region.title': '关于省市信息',
        'announcement.region.content': '2018年5月粗饼网取消选手所在城市显示，由于现在已无法从粗饼网获取选手城市，故而此后的选手在本站被作者归入了不存在的神手谷。目前使用的选手省市信息源自魔友赵吉波在取消前爬取的数据，非常感谢前辈留下的数据！',
        'announcement.launch.title': '网站上线',
        'announcement.launch.content': 'XCUBING网站正式上线运行，网站目前提供WCA赛事的赛季、现役、省市、综合排名及省市纪录功能，诚挚欢迎广大魔友积极体验并对网站在页面显示、功能使用等方面存在的问题和不足提出宝贵意见和建议。如您在访问网站过程中发现任何错误、故障，请及时通过以下方式反馈：作者邮箱：xcubing@qq.com。',
        'comp.select_events': '项目(点击选择)',
        'comp.current': '{source} - 已选{count}个项目 ({type})',
        'comp.calculating': '正在计算综合排名，请稍候...',
        'record.no_record': '暂无纪录',
        'all_cities': '全省',
    },

    // 繁体中文（基础翻译，基于简体转换，长文本需人工完善）
    'zh-TW': {
        'nav.home': '首頁',
        'nav.season': '賽季排名',
        'nav.active': '現役排名',
        'nav.region': '省市排名',
        'nav.comprehensive': '綜合排名',
        'nav.record': '省市紀錄',
        'season.title': '賽季排名',
        'active.title': '現役排名',
        'region.title': '省市排名',
        'comprehensive.title': '綜合排名',
        'record.title': '省市紀錄',
        'filter.region': '地區',
        'filter.project': '項目',
        'filter.gender': '性別',
        'filter.period': '時期',
        'filter.province': '省份',
        'filter.city': '城市',
        'filter.source': '排名類型',
        'filter.dataset': '時期',
        'gender.all': '所有',
        'gender.male': '男',
        'gender.female': '女',
        'gender.unknown': '未知',
        'btn.single': '單次',
        'btn.average': '平均',
        'btn.refresh': '重新整理',
        'table.rank': '排名',
        'table.name': '姓名',
        'table.country': '國家',
        'table.province': '省份',
        'table.city': '城市',
        'table.result': '成績',
        'table.competition': '比賽',
        'table.wcaid': 'WCA ID',
        'table.event': '項目',
        'table.events_count': '參與項目數',
        'table.total_rank': '排名總和',
        'current.single': '單次',
        'current.average': '平均',
        'current.historical': '歷史',
        'current.season': '賽季',
        'current.active': '現役',
        'loading': '載入中',
        'loading_failed': '資料載入失敗',
        'no_data': '暫無資料',
        'comp.select_events': '項目(點擊選擇)',
        'comp.current': '{source} - 已選{count}個項目 ({type})',
        'comp.calculating': '正在計算綜合排名，請稍候...',
        'record.no_record': '暫無紀錄',
        'all_cities': '全省',
    },

    // 以下为其他语言的基础翻译（短文本已尽力提供，长文本可后续完善）
    'ca': {
        'nav.home': 'Inici',
        'nav.season': 'Rànquings de Temporada',
        'nav.active': 'Rànquings Actius',
        'nav.region': 'Rànquings Regionals',
        'nav.comprehensive': 'Rànquings Comprensius',
        'nav.record': 'Rècords Regionals',
        'filter.region': 'Regió',
        'filter.project': 'Esdeveniment',
        'filter.gender': 'Gènere',
        'filter.period': 'Període',
        'filter.province': 'Província',
        'filter.city': 'Ciutat',
        'filter.source': 'Tipus de Rànquing',
        'filter.dataset': 'Subconjunt',
        'gender.all': 'Tots',
        'gender.male': 'Home',
        'gender.female': 'Dona',
        'gender.unknown': 'Desconegut',
        'btn.single': 'Individual',
        'btn.average': 'Mitjana',
        'btn.refresh': 'Actualitzar',
        'table.rank': 'Posició',
        'table.name': 'Nom',
        'table.country': 'País',
        'table.province': 'Província',
        'table.city': 'Ciutat',
        'table.result': 'Resultat',
        'table.competition': 'Competició',
        'table.wcaid': 'ID WCA',
        'table.event': 'Esdeveniment',
        'table.events_count': 'Esdeveniments',
        'table.total_rank': 'Suma de Posicions',
        'current.single': 'Individual',
        'current.average': 'Mitjana',
        'current.historical': 'Històric',
        'current.season': 'Temporada',
        'current.active': 'Actiu',
        'loading': 'Carregant',
        'loading_failed': 'Error en carregar les dades',
        'no_data': 'Sense dades',
        'comp.select_events': 'Selecciona esdeveniments (clic per triar)',
        'comp.current': '{source} - {count} esdeveniment(s) seleccionat(s) ({type})',
        'comp.calculating': 'Calculant rànquings comprensius, espereu...',
        'record.no_record': 'Sense rècord',
        'all_cities': 'Totes les ciutats de la província',
    },
    'cs': {
        'nav.home': 'Domů',
        'nav.season': 'Sezónní žebříčky',
        'nav.active': 'Aktivní žebříčky',
        'nav.region': 'Regionální žebříčky',
        'nav.comprehensive': 'Komplexní žebříčky',
        'nav.record': 'Regionální rekordy',
        'filter.region': 'Region',
        'filter.project': 'Disciplína',
        'filter.gender': 'Pohlaví',
        'filter.period': 'Období',
        'filter.province': 'Provincie',
        'filter.city': 'Město',
        'filter.source': 'Typ žebříčku',
        'filter.dataset': 'Podmnožina',
        'gender.all': 'Vše',
        'gender.male': 'Muž',
        'gender.female': 'Žena',
        'gender.unknown': 'Neznámé',
        'btn.single': 'Jednotlivě',
        'btn.average': 'Průměr',
        'btn.refresh': 'Obnovit',
        'table.rank': 'Pořadí',
        'table.name': 'Jméno',
        'table.country': 'Země',
        'table.province': 'Provincie',
        'table.city': 'Město',
        'table.result': 'Výsledek',
        'table.competition': 'Soutěž',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplína',
        'table.events_count': 'Disciplíny',
        'table.total_rank': 'Součet pořadí',
        'current.single': 'Jednotlivě',
        'current.average': 'Průměr',
        'current.historical': 'Historický',
        'current.season': 'Sezóna',
        'current.active': 'Aktivní',
        'loading': 'Načítání',
        'loading_failed': 'Načítání selhalo',
        'no_data': 'Žádná data',
        'comp.select_events': 'Vyberte disciplíny (kliknutím vyberete)',
        'comp.current': '{source} - vybráno {count} disciplín ({type})',
        'comp.calculating': 'Probíhá výpočet komplexního žebříčku, čekejte...',
        'record.no_record': 'Žádný rekord',
        'all_cities': 'Všechna města v provincii',
    },
    'da': {
        'nav.home': 'Hjem',
        'nav.season': 'Sæsonranglister',
        'nav.active': 'Aktive ranglister',
        'nav.region': 'Regionale ranglister',
        'nav.comprehensive': 'Omfattende ranglister',
        'nav.record': 'Regionale rekorder',
        'filter.region': 'Område',
        'filter.project': 'Disciplin',
        'filter.gender': 'Køn',
        'filter.period': 'Periode',
        'filter.province': 'Provins',
        'filter.city': 'By',
        'filter.source': 'Ranglistetype',
        'filter.dataset': 'Underdatasæt',
        'gender.all': 'Alle',
        'gender.male': 'Mand',
        'gender.female': 'Kvinde',
        'gender.unknown': 'Ukendt',
        'btn.single': 'Enkelt',
        'btn.average': 'Gennemsnit',
        'btn.refresh': 'Opdater',
        'table.rank': 'Placering',
        'table.name': 'Navn',
        'table.country': 'Land',
        'table.province': 'Provins',
        'table.city': 'By',
        'table.result': 'Resultat',
        'table.competition': 'Konkurrence',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplin',
        'table.events_count': 'Discipliner',
        'table.total_rank': 'Samlet placering',
        'current.single': 'Enkelt',
        'current.average': 'Gennemsnit',
        'current.historical': 'Historisk',
        'current.season': 'Sæson',
        'current.active': 'Aktiv',
        'loading': 'Indlæser',
        'loading_failed': 'Indlæsning mislykkedes',
        'no_data': 'Ingen data',
        'comp.select_events': 'Vælg discipliner (klik for at vælge)',
        'comp.current': '{source} - {count} disciplin(er) valgt ({type})',
        'comp.calculating': 'Beregner omfattende ranglister, vent venligst...',
        'record.no_record': 'Ingen rekord',
        'all_cities': 'Alle byer i provinsen',
    },
    'de': {
        'nav.home': 'Startseite',
        'nav.season': 'Saison-Rankings',
        'nav.active': 'Aktive Rankings',
        'nav.region': 'Regionale Rankings',
        'nav.comprehensive': 'Gesamtranglisten',
        'nav.record': 'Regionale Rekorde',
        'filter.region': 'Region',
        'filter.project': 'Disziplin',
        'filter.gender': 'Geschlecht',
        'filter.period': 'Zeitraum',
        'filter.province': 'Provinz',
        'filter.city': 'Stadt',
        'filter.source': 'Ranking-Typ',
        'filter.dataset': 'Teildatensatz',
        'gender.all': 'Alle',
        'gender.male': 'Männlich',
        'gender.female': 'Weiblich',
        'gender.unknown': 'Unbekannt',
        'btn.single': 'Einzel',
        'btn.average': 'Durchschnitt',
        'btn.refresh': 'Aktualisieren',
        'table.rank': 'Rang',
        'table.name': 'Name',
        'table.country': 'Land',
        'table.province': 'Provinz',
        'table.city': 'Stadt',
        'table.result': 'Ergebnis',
        'table.competition': 'Wettbewerb',
        'table.wcaid': 'WCA-ID',
        'table.event': 'Disziplin',
        'table.events_count': 'Disziplinen',
        'table.total_rank': 'Gesamtrang',
        'current.single': 'Einzel',
        'current.average': 'Durchschnitt',
        'current.historical': 'Historisch',
        'current.season': 'Saison',
        'current.active': 'Aktiv',
        'loading': 'Laden',
        'loading_failed': 'Laden fehlgeschlagen',
        'no_data': 'Keine Daten',
        'comp.select_events': 'Disziplinen auswählen (klicken zum Auswählen)',
        'comp.current': '{source} - {count} Disziplin(en) ausgewählt ({type})',
        'comp.calculating': 'Gesamtrangliste wird berechnet, bitte warten...',
        'record.no_record': 'Kein Rekord',
        'all_cities': 'Alle Städte in der Provinz',
    },
    'eo': {
        'nav.home': 'Ĉefpaĝo',
        'nav.season': 'Sezonaj Rangotabeloj',
        'nav.active': 'Aktivaj Rangotabeloj',
        'nav.region': 'Regionaj Rangotabeloj',
        'nav.comprehensive': 'Ĝeneralaj Rangotabeloj',
        'nav.record': 'Regionaj Rekordoj',
        'filter.region': 'Regiono',
        'filter.project': 'Disciplino',
        'filter.gender': 'Sekso',
        'filter.period': 'Periodo',
        'filter.province': 'Provinco',
        'filter.city': 'Urbo',
        'filter.source': 'Rangotabela Tipo',
        'filter.dataset': 'Subdatokolekto',
        'gender.all': 'Ĉiuj',
        'gender.male': 'Vira',
        'gender.female': 'Ina',
        'gender.unknown': 'Nekonata',
        'btn.single': 'Unuopa',
        'btn.average': 'Meznombro',
        'btn.refresh': 'Refreŝigi',
        'table.rank': 'Rango',
        'table.name': 'Nomo',
        'table.country': 'Lando',
        'table.province': 'Provinco',
        'table.city': 'Urbo',
        'table.result': 'Rezulto',
        'table.competition': 'Konkurso',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplino',
        'table.events_count': 'Disciplinoj',
        'table.total_rank': 'Suma Rango',
        'current.single': 'Unuopa',
        'current.average': 'Meznombro',
        'current.historical': 'Historia',
        'current.season': 'Sezono',
        'current.active': 'Aktiva',
        'loading': 'Ŝarĝante',
        'loading_failed': 'Ŝarĝo malsukcesis',
        'no_data': 'Neniuj datumoj',
        'comp.select_events': 'Elektu disciplinojn (alklaku por elekti)',
        'comp.current': '{source} - {count} elektita(j) disciplino(j) ({type})',
        'comp.calculating': 'Kalkulante ĝeneralajn rangotabelojn, bonvolu atendi...',
        'record.no_record': 'Nenia rekordo',
        'all_cities': 'Ĉiuj urboj en la provinco',
    },
    'es-ES': {
        'nav.home': 'Inicio',
        'nav.season': 'Rankings de Temporada',
        'nav.active': 'Rankings Activos',
        'nav.region': 'Rankings Regionales',
        'nav.comprehensive': 'Rankings Integrales',
        'nav.record': 'Récords Regionales',
        'filter.region': 'Región',
        'filter.project': 'Evento',
        'filter.gender': 'Género',
        'filter.period': 'Período',
        'filter.province': 'Provincia',
        'filter.city': 'Ciudad',
        'filter.source': 'Tipo de Ranking',
        'filter.dataset': 'Subconjunto',
        'gender.all': 'Todos',
        'gender.male': 'Hombre',
        'gender.female': 'Mujer',
        'gender.unknown': 'Desconocido',
        'btn.single': 'Individual',
        'btn.average': 'Promedio',
        'btn.refresh': 'Actualizar',
        'table.rank': 'Posición',
        'table.name': 'Nombre',
        'table.country': 'País',
        'table.province': 'Provincia',
        'table.city': 'Ciudad',
        'table.result': 'Resultado',
        'table.competition': 'Competición',
        'table.wcaid': 'ID WCA',
        'table.event': 'Evento',
        'table.events_count': 'Eventos',
        'table.total_rank': 'Suma de Posiciones',
        'current.single': 'Individual',
        'current.average': 'Promedio',
        'current.historical': 'Histórico',
        'current.season': 'Temporada',
        'current.active': 'Activo',
        'loading': 'Cargando',
        'loading_failed': 'Error al cargar datos',
        'no_data': 'Sin datos',
        'comp.select_events': 'Selecciona eventos (clic para elegir)',
        'comp.current': '{source} - {count} evento(s) seleccionado(s) ({type})',
        'comp.calculating': 'Calculando rankings integrales, espere...',
        'record.no_record': 'Sin récord',
        'all_cities': 'Todas las ciudades de la provincia',
    },
    'es-419': {
        // 拉丁美洲西班牙语，与西班牙语略有差异，但可复用大部分
        'nav.home': 'Inicio',
        'nav.season': 'Rankings de Temporada',
        'nav.active': 'Rankings Activos',
        'nav.region': 'Rankings Regionales',
        'nav.comprehensive': 'Rankings Integrales',
        'nav.record': 'Récords Regionales',
        'filter.region': 'Región',
        'filter.project': 'Evento',
        'filter.gender': 'Género',
        'filter.period': 'Período',
        'filter.province': 'Provincia',
        'filter.city': 'Ciudad',
        'filter.source': 'Tipo de Ranking',
        'filter.dataset': 'Subconjunto',
        'gender.all': 'Todos',
        'gender.male': 'Hombre',
        'gender.female': 'Mujer',
        'gender.unknown': 'Desconocido',
        'btn.single': 'Individual',
        'btn.average': 'Promedio',
        'btn.refresh': 'Actualizar',
        'table.rank': 'Posición',
        'table.name': 'Nombre',
        'table.country': 'País',
        'table.province': 'Provincia',
        'table.city': 'Ciudad',
        'table.result': 'Resultado',
        'table.competition': 'Competencia',
        'table.wcaid': 'ID WCA',
        'table.event': 'Evento',
        'table.events_count': 'Eventos',
        'table.total_rank': 'Suma de Posiciones',
        'current.single': 'Individual',
        'current.average': 'Promedio',
        'current.historical': 'Histórico',
        'current.season': 'Temporada',
        'current.active': 'Activo',
        'loading': 'Cargando',
        'loading_failed': 'Error al cargar datos',
        'no_data': 'Sin datos',
        'comp.select_events': 'Selecciona eventos (clic para elegir)',
        'comp.current': '{source} - {count} evento(s) seleccionado(s) ({type})',
        'comp.calculating': 'Calculando rankings integrales, espere...',
        'record.no_record': 'Sin récord',
        'all_cities': 'Todas las ciudades de la provincia',
    },
    'eu': {
        'nav.home': 'Hasiera',
        'nav.season': 'Denboraldiko sailkapenak',
        'nav.active': 'Sailkapen aktiboak',
        'nav.region': 'Eskualdeko sailkapenak',
        'nav.comprehensive': 'Sailkapen integralak',
        'nav.record': 'Eskualdeko errekorrak',
        'filter.region': 'Eskualdea',
        'filter.project': 'Proba',
        'filter.gender': 'Generoa',
        'filter.period': 'Epea',
        'filter.province': 'Probintzia',
        'filter.city': 'Hiria',
        'filter.source': 'Sailkapen mota',
        'filter.dataset': 'Azpimultzoa',
        'gender.all': 'Guztiak',
        'gender.male': 'Gizona',
        'gender.female': 'Emakumea',
        'gender.unknown': 'Ezezaguna',
        'btn.single': 'Bakarka',
        'btn.average': 'Batezbestekoa',
        'btn.refresh': 'Freskatu',
        'table.rank': 'Postua',
        'table.name': 'Izena',
        'table.country': 'Herrialdea',
        'table.province': 'Probintzia',
        'table.city': 'Hiria',
        'table.result': 'Emaitza',
        'table.competition': 'Lehiaketa',
        'table.wcaid': 'WCA ID',
        'table.event': 'Proba',
        'table.events_count': 'Probak',
        'table.total_rank': 'Postuen batura',
        'current.single': 'Bakarka',
        'current.average': 'Batezbestekoa',
        'current.historical': 'Historikoa',
        'current.season': 'Denboraldia',
        'current.active': 'Aktiboa',
        'loading': 'Kargatzen',
        'loading_failed': 'Kargatzeak huts egin du',
        'no_data': 'Daturik ez',
        'comp.select_events': 'Hautatu probak (klik egin aukeratzeko)',
        'comp.current': '{source} - {count} proba hautatu dira ({type})',
        'comp.calculating': 'Sailkapen integralak kalkulatzen, itxaron mesedez...',
        'record.no_record': 'Errekorrik ez',
        'all_cities': 'Probintziako hiri guztiak',
    },
    'fi': {
        'nav.home': 'Koti',
        'nav.season': 'Kauden rankingit',
        'nav.active': 'Aktiiviset rankingit',
        'nav.region': 'Alueelliset rankingit',
        'nav.comprehensive': 'Kattavat rankingit',
        'nav.record': 'Alueelliset ennätykset',
        'filter.region': 'Alue',
        'filter.project': 'Laji',
        'filter.gender': 'Sukupuoli',
        'filter.period': 'Ajanjakso',
        'filter.province': 'Maakunta',
        'filter.city': 'Kaupunki',
        'filter.source': 'Ranking-tyyppi',
        'filter.dataset': 'Osajoukko',
        'gender.all': 'Kaikki',
        'gender.male': 'Mies',
        'gender.female': 'Nainen',
        'gender.unknown': 'Tuntematon',
        'btn.single': 'Yksittäinen',
        'btn.average': 'Keskiarvo',
        'btn.refresh': 'Päivitä',
        'table.rank': 'Sijoitus',
        'table.name': 'Nimi',
        'table.country': 'Maa',
        'table.province': 'Maakunta',
        'table.city': 'Kaupunki',
        'table.result': 'Tulos',
        'table.competition': 'Kilpailu',
        'table.wcaid': 'WCA-tunnus',
        'table.event': 'Laji',
        'table.events_count': 'Lajit',
        'table.total_rank': 'Sijoitusten summa',
        'current.single': 'Yksittäinen',
        'current.average': 'Keskiarvo',
        'current.historical': 'Historiallinen',
        'current.season': 'Kausi',
        'current.active': 'Aktiivinen',
        'loading': 'Ladataan',
        'loading_failed': 'Tietojen lataus epäonnistui',
        'no_data': 'Ei tietoja',
        'comp.select_events': 'Valitse lajit (klikkaa valitaksesi)',
        'comp.current': '{source} - {count} lajia valittu ({type})',
        'comp.calculating': 'Lasketaan kattavia rankingeja, odota...',
        'record.no_record': 'Ei ennätystä',
        'all_cities': 'Kaikki maakunnan kaupungit',
    },
    'fr': {
        'nav.home': 'Accueil',
        'nav.season': 'Classements de saison',
        'nav.active': 'Classements actifs',
        'nav.region': 'Classements régionaux',
        'nav.comprehensive': 'Classements complets',
        'nav.record': 'Records régionaux',
        'filter.region': 'Région',
        'filter.project': 'Épreuve',
        'filter.gender': 'Genre',
        'filter.period': 'Période',
        'filter.province': 'Province',
        'filter.city': 'Ville',
        'filter.source': 'Type de classement',
        'filter.dataset': 'Sous-ensemble',
        'gender.all': 'Tous',
        'gender.male': 'Homme',
        'gender.female': 'Femme',
        'gender.unknown': 'Inconnu',
        'btn.single': 'Simple',
        'btn.average': 'Moyenne',
        'btn.refresh': 'Actualiser',
        'table.rank': 'Rang',
        'table.name': 'Nom',
        'table.country': 'Pays',
        'table.province': 'Province',
        'table.city': 'Ville',
        'table.result': 'Résultat',
        'table.competition': 'Compétition',
        'table.wcaid': 'ID WCA',
        'table.event': 'Épreuve',
        'table.events_count': 'Épreuves',
        'table.total_rank': 'Somme des rangs',
        'current.single': 'Simple',
        'current.average': 'Moyenne',
        'current.historical': 'Historique',
        'current.season': 'Saison',
        'current.active': 'Actif',
        'loading': 'Chargement',
        'loading_failed': 'Échec du chargement',
        'no_data': 'Aucune donnée',
        'comp.select_events': 'Sélectionnez les épreuves (cliquez pour choisir)',
        'comp.current': '{source} - {count} épreuve(s) sélectionnée(s) ({type})',
        'comp.calculating': 'Calcul des classements complets, veuillez patienter...',
        'record.no_record': 'Aucun record',
        'all_cities': 'Toutes les villes de la province',
    },
    'fr-CA': {
        // 加拿大法语，与法国法语基本一致，可复用
        'nav.home': 'Accueil',
        'nav.season': 'Classements de saison',
        'nav.active': 'Classements actifs',
        'nav.region': 'Classements régionaux',
        'nav.comprehensive': 'Classements complets',
        'nav.record': 'Records régionaux',
        'filter.region': 'Région',
        'filter.project': 'Épreuve',
        'filter.gender': 'Genre',
        'filter.period': 'Période',
        'filter.province': 'Province',
        'filter.city': 'Ville',
        'filter.source': 'Type de classement',
        'filter.dataset': 'Sous-ensemble',
        'gender.all': 'Tous',
        'gender.male': 'Homme',
        'gender.female': 'Femme',
        'gender.unknown': 'Inconnu',
        'btn.single': 'Simple',
        'btn.average': 'Moyenne',
        'btn.refresh': 'Actualiser',
        'table.rank': 'Rang',
        'table.name': 'Nom',
        'table.country': 'Pays',
        'table.province': 'Province',
        'table.city': 'Ville',
        'table.result': 'Résultat',
        'table.competition': 'Compétition',
        'table.wcaid': 'ID WCA',
        'table.event': 'Épreuve',
        'table.events_count': 'Épreuves',
        'table.total_rank': 'Somme des rangs',
        'current.single': 'Simple',
        'current.average': 'Moyenne',
        'current.historical': 'Historique',
        'current.season': 'Saison',
        'current.active': 'Actif',
        'loading': 'Chargement',
        'loading_failed': 'Échec du chargement',
        'no_data': 'Aucune donnée',
        'comp.select_events': 'Sélectionnez les épreuves (cliquez pour choisir)',
        'comp.current': '{source} - {count} épreuve(s) sélectionnée(s) ({type})',
        'comp.calculating': 'Calcul des classements complets, veuillez patienter...',
        'record.no_record': 'Aucun record',
        'all_cities': 'Toutes les villes de la province',
    },
    'hr': {
        'nav.home': 'Početna',
        'nav.season': 'Sezonske ljestvice',
        'nav.active': 'Aktivne ljestvice',
        'nav.region': 'Regionalne ljestvice',
        'nav.comprehensive': 'Sveobuhvatne ljestvice',
        'nav.record': 'Regionalni rekordi',
        'filter.region': 'Regija',
        'filter.project': 'Disciplina',
        'filter.gender': 'Spol',
        'filter.period': 'Razdoblje',
        'filter.province': 'Pokrajina',
        'filter.city': 'Grad',
        'filter.source': 'Vrsta ljestvice',
        'filter.dataset': 'Podskup',
        'gender.all': 'Svi',
        'gender.male': 'Muško',
        'gender.female': 'Žensko',
        'gender.unknown': 'Nepoznato',
        'btn.single': 'Pojedinačno',
        'btn.average': 'Prosjek',
        'btn.refresh': 'Osvježi',
        'table.rank': 'Rang',
        'table.name': 'Ime',
        'table.country': 'Država',
        'table.province': 'Pokrajina',
        'table.city': 'Grad',
        'table.result': 'Rezultat',
        'table.competition': 'Natjecanje',
        'table.wcaid': 'WCA ID',
        'table.event': 'Disciplina',
        'table.events_count': 'Discipline',
        'table.total_rank': 'Zbroj rangova',
        'current.single': 'Pojedinačno',
        'current.average': 'Prosjek',
        'current.historical': 'Povijesno',
        'current.season': 'Sezona',
        'current.active': 'Aktivno',
        'loading': 'Učitavanje',
        'loading_failed': 'Učitavanje nije uspjelo',
        'no_data': 'Nema podataka',
        'comp.select_events': 'Odaberite discipline (klikom odaberite)',
        'comp.current': '{source} - odabrano {count} disciplina ({type})',
        'comp.calculating': 'Izračunavam sveobuhvatne ljestvice, pričekajte...',
        'record.no_record': 'Nema rekorda',
        'all_cities': 'Svi gradovi u pokrajini',
    },
    'hu': {
        'nav.home': 'Kezdőlap',
        'nav.season': 'Szezonális ranglisták',
        'nav.active': 'Aktív ranglisták',
        'nav.region': 'Regionális ranglisták',
        'nav.comprehensive': 'Átfogó ranglisták',
        'nav.record': 'Regionális rekordok',
        'filter.region': 'Régió',
        'filter.project': 'Szám',
        'filter.gender': 'Nem',
        'filter.period': 'Időszak',
        'filter.province': 'Tartomány',
        'filter.city': 'Város',
        'filter.source': 'Ranglista típusa',
        'filter.dataset': 'Alhalmaz',
        'gender.all': 'Mind',
        'gender.male': 'Férfi',
        'gender.female': 'Nő',
        'gender.unknown': 'Ismeretlen',
        'btn.single': 'Egyéni',
        'btn.average': 'Átlag',
        'btn.refresh': 'Frissítés',
        'table.rank': 'Helyezés',
        'table.name': 'Név',
        'table.country': 'Ország',
        'table.province': 'Tartomány',
        'table.city': 'Város',
        'table.result': 'Eredmény',
        'table.competition': 'Versen